### ISSUE TITLE
Add front end validation of fields

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#103]
Each input field should have reasonable and appropriate limits to what, and how much, data can be placed there.

Exactly where the validation happens is less important than taking steps to ensure that the user can be aware of where the limit is hit, and possibly what that limit is.

\[ for original description, see [this comment](https://github.com/mozilla-lockbox/lockbox-extension/issues/103#issuecomment-338262084)]

**Comment by jimporter** [comment]
The only validation I think we really need is on the origin field. Nothing else should actually cause *problems*, and I don't think we should restrict what users can do if we don't actually need to. Eventually, we'll have password auto-generation, and if a user just wanted to have a list of passwords that they remember (e.g. "I use the password starting with 'A' on sites X, Y, and Z"), that's up to them.

**Comment by linuxwolf** [comment]
I've updated the original description to try and to be more about limits.

Limits are important, though.  (Ab)users will try to break things, and the most common is to try to overflow any open-ended fields.

**Comment by linuxwolf** [comment]
_\[ this is the original description, moved to a comment]_

**ORIGINAL:**
A suggestion from @pdehaan at https://github.com/mozilla-lockbox/lockbox-extension/pull/98#issuecomment-331312078 to consider:

>should we make at least one field in the Add form required? Currently I can add infinite number of new records where I don't fill in any content and all the results just say "(no title)" / "(no username)"

**Comment by linuxwolf** [comment]
As a starting point for consideration:

* **title**, **origin**, **username**, **password** := limited to ~500 characters
* **notes** := limited to 10,000 characters

**Comment by sandysage** [comment]
Issue #190 should be addressed with PR #168
