### ISSUE TITLE
Display favicons for each result?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#104]
I currently use 1Password religiously, and have about 550 logins.
It may be nice to display a favicon for each result, next to the title/origin for easier scanning.

<img width="387" alt="menubar_and_1password" src="https://user-images.githubusercontent.com/557895/30765188-3e984526-9fa3-11e7-8602-3830e69c4698.png">

**Comment by jimporter** [comment]
Yeah, this is in a doc somewhere. We should probably move all those things to the issue tracker.

**Comment by devinreams** [comment]
Thanks for opening this up. This is definitely considered and being discussed and tracked at #253
