### ISSUE TITLE
Update dependencies before alpha release

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#129]
Most notable is React 16, which has a ~30% reduction in file size. That should help us load our extension's pages a bit faster.

---

- [ ] prune unpopular/unsupported packages
- [ ] review outdated packages (and decide to update them)
  - [ ] decide on updating React 16 now vs later
- [ ] review dependencies vs devdependencies for appropriateness (css-loader, style-loader)
- [ ] decide to pin lockbox-datastore to a tag?

**Comment by jimporter** [comment]
Now would probably also be a good time to prune packages that aren't especially "popular", for lack of a better word. If we use more-mainstream packages, we have a greater degree of certainty that other people are finding issues with them so we're not the ones who have to stumble on random bugs. High up on the list of things to remove:

* `async-wait-until`
* `nodezip`
* `xml-webpack-plugin`
* `react-addons-test-utils` (it's deprecated!)

**Comment by pdehaan** [comment]
Current list of deprecated packages:

```sh
$ npm outdated

Package                         Current      Wanted  Latest  Location
copy-webpack-plugin               4.0.1       4.1.0   4.1.0  lockbox
enzyme                            2.9.1       2.9.1   3.1.0  lockbox
eslint                            4.7.1       4.8.0   4.8.0  lockbox
eslint-plugin-node                5.1.1       5.2.0   5.2.0  lockbox
eslint-plugin-react               7.3.0       7.4.0   7.4.0  lockbox
extract-text-webpack-plugin       3.0.0       3.0.1   3.0.1  lockbox
jsdom                            11.2.0      11.3.0  11.3.0  lockbox
lockbox-datastore                 0.0.1         git     git  lockbox
mocha                             3.5.3       3.5.3   4.0.0  lockbox
mocha-webpack                1.0.0-rc.1  1.0.0-rc.1   0.7.0  lockbox
prop-types                      15.5.10      15.6.0  15.6.0  lockbox
react                            15.6.1      15.6.2  16.0.0  lockbox
react-addons-test-utils          15.6.0      15.6.2  15.6.2  lockbox
react-dom                        15.6.1      15.6.2  16.0.0  lockbox
sinon                             3.3.0       3.3.0   4.0.1  lockbox
sinon-chai                       2.13.0      2.14.0  2.14.0  lockbox
source-map-support               0.4.18      0.4.18   0.5.0  lockbox
style-loader                     0.18.2      0.18.2  0.19.0  lockbox
```

A couple other random observations... Per the package.json `dependencies` below, it _feels_ like `css-loader` and `style-loader` should probably be devDeps instead. Plus, setting a git repo as a direct dependency feels sketchy. Not sure if we want to publish the repo as a npm package so we can use semver. Or conversely, pin the **lockbox-datastore** dependency to a git SHA so we aren't always on the bleeding edge of the repo.

```json
  "dependencies": {
    "css-loader": "^0.28.7",
    "fluent": "^0.4.1",
    "fluent-intl-polyfill": "^0.1.0",
    "fluent-langneg": "^0.1.0",
    "fluent-react": "^0.4.1",
    "intl-pluralrules": "^0.1.0",
    "lockbox-datastore": "git+https://github.com/mozilla-lockbox/lockbox-datastore.git",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-copy-to-clipboard": "^5.0.0",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "style-loader": "^0.18.2"
  },
```

**Comment by jimporter** [comment]
`lockbox-datastore` is actually pinned, but it's through `package-lock.json`.

**Comment by linuxwolf** [comment]
@pdehaan It should be pinned to a tag.  It hasn't been yet because we're eyebrow deep in alpha development.

Publishing it on NPM might be ok *eventually*, but not anytime soon.

**Comment by pdehaan** [comment]
Re: **react@16**, just saw this gem posted in a TestPilot bug: https://blog.discordapp.com/lessons-from-migrating-a-large-codebase-to-react-16-e60e49102aa6

**Comment by devinreams** [comment]
@jimporter @linuxwolf @pdehaan I made a quick "todo list" up in the original description ☝️ based on what I saw discussed here so we can track progress/decisions as we go:

- [ ] prune unpopular/unsupported packages
- [ ] review outdated packages (and decide to update them)
  - [ ] decide on updating React 16 now vs later
- [ ] review dependencies vs devdependencies for appropriateness (css-loader, style-loader)
- [ ] decide to pin lockbox-datastore to a tag?

Feel free to add/update however is helpful for you to keep organized.
