### ISSUE TITLE
Add "send feedback" button to extension

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#130]

**Comment by devinreams** [comment]
@jimporter wired up a placeholder button at #154 🥇 

Now we just need the actual URL to open when clicked from @sandysage

**Comment by sandysage** [comment]
Survey is here: https://qsurvey.mozilla.com/s3/Lockbox-Input

SN: Ideally I'll have my own account at the end of this week, or possibly the beginning of next, to be able to edit and manage this feedback form.
