### ISSUE TITLE
User interface to reset/clean database

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#137]
To re-install, wipe data, get out of a broken situation during testing?, etc.

**Comment by linuxwolf** [comment]
I think this belongs in a Options or Settings page.  However this is labeled visually, the behavior should be "start over":

* (standard or enhanced) confirm with the user 
* close all open views
* reset the datastore
* open firstrun view

@changecourse  @devinreams  @jimporter Thoughts?

**Comment by devinreams** [comment]
>I think this belongs in a Options or Settings page

I definitely agree this should live on the start of a [options_ui page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/options_ui):

- should be hidden "enough" from users so they don't get curious
- needs to be available if you can't get to the extension/page/whatever (its broken)

>the behavior should be "start over"

I can't think of anything else it needs to do... 👍

**Comment by linuxwolf** [comment]
Question: should this also include tossing out any FxA information we've gathered?

My initial inclination is "no", but then it's not quite "start over" at that point.

More thoughts @devinreams @changecourse @irrationalagent @jimporter ?

**Comment by irrationalagent** [comment]
from a metrics perspective:

if someone starts over and then uses a new fxa id for their second go at it, then sends us a ping, they will appear to us as a new user if we go the true "full wipe" path. but hopefully this wouldnt happen enough to really distort the numbers.

however, if we persist the "old" fxa uid through the wipe, and then they sign in with a new account, then that might cause other problems... for one, we'd have to somehow overwrite the new id with the old i think? 

maybe persisting would be OK if we have a "wipe event" or similar so that we know when this happens.

**Comment by linuxwolf** [comment]
> however, if we persist the "old" fxa uid through the wipe, and then they sign in with a new account, then that might cause other problems... for one, we'd have to somehow overwrite the new id with the old i think?

In the current implementation, the  extension will overwrite the previous FxA info with the new info.

I'm a little worried about "sort of" keeping information (we'll have lost their password so we'll have to prompt all over again) ... we can explain it, but that doesn't mean the user will understand.

**Comment by devinreams** [comment]
>>Question: should this (for alpha) also include tossing out any FxA information we've gathered?

>they will appear to us as a new user if we go the true "full wipe" path. but hopefully this wouldnt happen enough to really distort the numbers.

It seems like congruent "full wipe" or "reset" behavior is to **fully remove existing data**, requiring users setting _everything_  back up and not holding onto anything.

**Comment by linuxwolf** [comment]
@jimporter I'll need some help on how to properly use a modal dialog here.
