### ISSUE TITLE
Report extension CI status to Treeherder

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#14]
http://treeherder.readthedocs.io/submitting_data.html#add-github-repo ?

**Comment by devinreams** [comment]
@m8ttyB in your opinion, is it still worth reporting into [Treeherder](https://github.com/mozilla/treeherder/blob/master/treeherder/model/fixtures/repository.json)?

I may be overlooking something but GitHub repos really just spit out commit history and no more (build status, binaries/releases, etc.).

**Comment by m8ttyB** [comment]
Truthfully, no. I think at this point it's added reporting and process that we wouldn't use.

**Comment by m8ttyB** [comment]
I've done a bit of investigation, we do have this enabled on other projects. Again I think for us it would add little value atm.

**Comment by devinreams** [comment]
Yeah when I look at the [GitHub repos](https://github.com/mozilla/treeherder/blob/master/treeherder/model/fixtures/repository.json) like [autopush](https://treeherder.mozilla.org/#/jobs?repo=autopush) I also concluded it wouldn't add much value at all.

Thanks for double checking.
