### ISSUE TITLE
Only allow one editor view of lockbox open at a time

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#151]
After doing some testing with the current build, as well as trying to evaluate how the lock/unlock functionality will work (both in the popover as well as the tab) I worry that it will create some confusion with having multiple versions of the entry list open at a time, each in potentially different states... If the user locks lockbox in one tab, it still requires a refresh in the other tabs to take effect, and the user is left to wonder whether or not the entries are still accessible in a 'locked' state.

**Comment by jimporter** [comment]
We can lock background tabs without any issues. I vastly prefer allowing multiple management tabs, since it makes it possible to view one item while editing another (e.g. to copy notes across).

**Comment by changecourse** [comment]
I hear you about copying/pasting between different entries, and yes, allowing multiple tabs to be open would help in this, but I don't think that use case outweighs the confusion or potential for concern around visibility of their lockbox (even if we lock it).

We're making some big assumptions about...
1. someone using the notes field for an entry (it's not a core part of the username/password/url equation)
2. someone also wanting to copy and paste things like notes across multiple entries

I think we should default to one view, not risk user confusion around multiple tabs, and then check analytics around alpha usage to inform some of the use cases you're concerned about for the future.

**Comment by jimporter** [comment]
> I think we should default to one view, not risk user confusion around multiple tabs, and then check analytics around alpha usage to inform some of the use cases you're concerned about for the future.

If we're doing analytics for this, wouldn't it be easier for now if we allowed multiple views so we could track if people actually used them? Switching over to a single view should be easy in the future, since we already have code to do that for first-run.

**Comment by changecourse** [comment]
I would need to understand what we'd be tracking... numbers around how many instances of "multiple tabs open" may not be valuable, because someone could have done that by accident, in its current state. 

Would we track instances of multiple tabs open where fields were copied and pasted between tabs? 

I think this all comes down to hypotheses and which is more important to ensure... the potential for compromising a user's trust/understanding of the security of their lockbox, or the potential for users to copy/paste in a slightly more convenient way between entries (which I still don't believe to be a common use case)

**Comment by jimporter** [comment]
We could track when tabs are focused/unfocused (or when they're part of different windows) and what actions people are performing in each. From there, we could probably get a pretty good idea if people are using multiple editors at once. We could also just ask for feedback on it, since this is pretty early on.

Using a single editor window does come with some extra costs though, especially if we want a popup UI later. If you have the editor open in the background and you're editing something, but then go to a tab, open the popup, and click "edit" on another entry, we'd have to interrupt the user by asking them what they want to do with the entry they were previously editing. With multiple views, we could avoid that for free.

**Comment by changecourse** [comment]
@irrationalagent could you weigh in on telemetry coverage for this use case?

I do think that once we add the popover action (on toolbar icon click) the possibility of multiple tabs will be drastically reduced (if we want it to be possible)... as you'd only be able to access the tab by clicking within the popover each time... 

It may make sense for others to weigh in... not wanting this to be a big hindrance ahead of alpha release...

**Comment by devinreams** [comment]
From today's call from @jimporter:

- Click the browser action button to open editor is not how users will likely be "reading" long-term
  - eg: users may not open this CRUD editor much
- No evidence users will be confused, easier to find and test that if it's there (and introduces the confusion)
  - counter point from @sandysage: would rather an explicit use case as to why to support this
- @irrationalagent pointed out: we need a way to then know multiple tabs were opened (not currently planning, not even tracking closure of a tab) - would require more work to track accurately
- @devinreams witnessed someone (very technical) start this for the first time and click the button twice and say "well that's interesting.." when seeing multiple tabs (unexpected, jarring)

We decided another conversation is needed to come to decision...

**Comment by sandysage** [comment]
Clarifying my point: I propose eliciting a specific use case from our intended audience, the (privacy vulnerable) [those laboring on the Internet with fundamentally misinformed views about privacy and security], to drive that workflow.

Since both approaches are based on hypotheses around user behavior, I suggest we proceed with UX, @changecourse leading the direction. And then we test it, both with user research and feedback form opportunities.

I'm open to continuing the conversation here in the GitHub issue, or if it works better, let's grab a time today to discuss more. I'm looking to have this issue resolved prior to Alpha release.

**Comment by sandysage** [comment]
To sum up the points made here:

### Pros of changing to single tab editor view
* eliminates the potential risk of confusion with multiple tabs
* eliminates maintaining multiple states and reconciling those
* avoids the risk of user confusion --> distrust which is a higher risk than a more convenient way to switch between entries
* no extra metrics work needed at this time

### Cons of changing to single tab editor view
* makes it harder to copy/paste notes and other data between tabs (not impossible, but not optimized for)
* dictates the user flow up-front versus just opening up every possible user journey and measuring to see if/where users get stuck
* users may not open this CRUD editor much, when the browser action leads to the read only pop-over, so multiple editor views _shouldn't_ happen often

Given who our users are,  let's proceed with the single editor view. Moving this to 'todo' for Alpha.

**Comment by devinreams** [comment]
Thanks for helping weigh the pros/cons @sandysage @changecourse.

While I see both sides, I can appreciate our targeted "privacy vulnerable" audience is where we should continue to orient ourselves and decisions like this.

Thanks @jimporter @changecourse @sandysage for working together to come up with whats best for our audience and still allowing for testing, changes, and further experimentation.
