### ISSUE TITLE
Condense the first run to one verify (no finished) page

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#155]
Adding issue to discuss and prioritize eliminating this extra "Done" page.

---

To reduce the friction for users to  "get started" (sign in to FxA and confirm password) the proposed UX entirely drops `FinishedPage3` and jumps straight into the editor:

Mockup: https://mozilla.invisionapp.com/share/5JDP20NYB#/screens/256733361

Current code: https://github.com/mozilla-lockbox/lockbox-extension/blob/master/src/webextension/firstrun/components/pages.js#L119

**Comment by devinreams** [comment]
@jimporter looking at FinishedPaged3, would it take much to collapse that into `VerifyPage2` and just open directly to the editor?

https://github.com/mozilla-lockbox/lockbox-extension/blob/8e0739b16e5a93b785f780fb34174453852b61a8/src/webextension/firstrun/components/pages.js#L120-L151

If the answer is "no, it wouldn't really take much" then @sandysage and @changecourse agree with you: we'd like to schedule this as a todo before Alpha.

**Comment by linuxwolf** [comment]
Fixed by #177
