### ISSUE TITLE
Lockbox should be usuable when resized to a small window

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#159]
Resizing the browser window makes navigation of a user's items unusable.

<img width="617" alt="screen shot 2017-10-11 at 9 17 38 am" src="https://user-images.githubusercontent.com/63193/31449886-4ee4ae58-ae65-11e7-8e01-95e3200c3b19.png">

**Comment by jimporter** [comment]
Resolved in #154
