### ISSUE TITLE
Unable to login after entering incorrect credentials

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#160]
I'm able to trigger a state where I cannot login and no information is given to user why their credentials, even when valid, are prevented from logging into Lockbox.

Moved conversation from https://github.com/mozilla-lockbox/lockbox-extension/pull/157#issuecomment-335842414 to here.

Viewing the console, I see this error:
`verify failed: password verification request failed: Client has sent too many requests`

* What is the rate limit?
* Is there a plan to expose a more useful error message?

1. Using a previously verified FxA account, using incorrect credentials with the FxA popup triggers FxA to send an account verification code that must be copy/pasted into the popup to proceed. Once this is accomplished, the user is directed to `Confirm your Lockbox Password`. Entering a correct password fails with the error message `wrong password`.

![fxa_popup](https://user-images.githubusercontent.com/63193/31455500-f96e2e62-ae74-11e7-9f4a-636c14e988ce.gif)

2.  Using a previously verified FxA account, use the correct credentials to login to the FxA popup. Once the user is directed to `Confirm your Lockbox Password`. Enter incorrect passwords several times, followed by the correct credentials. When the correct credentials are submitted, Lockbox fails to log in and continues to present the user with the error message `wrong password`.

![lockboxk_confirm_password](https://user-images.githubusercontent.com/63193/31455536-1eb482c0-ae75-11e7-8562-2fd131a00c5d.gif)

**Comment by linuxwolf** [comment]
"Fixed" by #177 

Since FxA is no longer in the flow, it's not relevant.  This issue might need to be re-opened when FxA is brought back.
