### ISSUE TITLE
Plan UI changes to match mockups

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#166]
After Alpha is release, to discuss scope of design and style changes for the user interface.

- [x] #255
- [x] #256 
- [x] #265

# Visual Design
https://mozilla.invisionapp.com/share/MHEBCD4PK#/screens/262028719

**Comment by changecourse** [comment]
As part of the impending go/no go discussion today, I recommend that we move the milestone for this issue, or close, in favor of a more comprehensive set of issues addressing the visual look and feel of the product for 0.1.2

**Comment by sandysage** [comment]
- [ ] #255
- [ ] #256

**Comment by devinreams** [comment]
@changecourse we're prioritizing the two you pointed out this week (typography, inputs). we also spun up an issue to tackle button styles at the same, feel free to contribute if we overlooked anything: #265

**Comment by m8ttyB** [comment]
Added the `epic` to the [Layout test suite](https://testrail.stage.mozaws.net/index.php?/suites/view/1642) in TestRail.

**Comment by sandysage** [comment]
- Favicon display is it's own 'feature' and is not included as part of this epic, and is tracked in #253 
- First-run landing screen + initial action (create first account) are not included as part of this epic and is tracked in #292

**Comment by devinreams** [comment]
All three of these are expected to land in 0.1.2.

-    #255
-   #256
 -  #265

As this epic is currently defined, I believe that means its complete and follow-up issues can be created accordingly. Or more added to this if preferred.

**Comment by changecourse** [comment]
Closing as this issue is outdated at this point and other issues have covered many of the changes discussed here already.

**Comment by sandysage** [comment]
![giphy](https://user-images.githubusercontent.com/850418/32679712-9e74dc64-c624-11e7-935f-eb4323cb2211.gif)
