### ISSUE TITLE
Update OAuth Details to FxA Production

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#174]
The current client registration is against a development environment, which requires all users to create new (and potentially confusing) accounts for what is perceived to be the same service.  Instead, the client details need to be for the production service.

Related to #209

**Comment by linuxwolf** [comment]
This is on hold until the client is provisioned.

**Comment by rfk** [comment]
Credentials provisioning bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1407500

**Comment by devinreams** [comment]
@linuxwolf as discussed: this issue is actually completed and live as part of #362, right?

**Comment by linuxwolf** [comment]
@devinreams That is correct.
