### ISSUE TITLE
Extension fails to start because Telemetry events are already registered

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#180]
When the extension starts, it can fail because the call to `Telemetry.registerEvents()` fails -- due to events already existing.

Opening an issue to allow collaboration on and visibility on #175.

**Comment by linuxwolf** [comment]
The proposed workaround is to version the telemetry record object for now.

This workaround can be reverted once Telemeyry supports `unregisterEvents`.

**Comment by sandysage** [comment]
Worth noting, the reason for this work around is that Telemetry does not support Services.telemetry.unregisterEvents which is being addressed in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1408975

**Comment by sandysage** [comment]
This was merged: https://github.com/mozilla-lockbox/lockbox-extension/pull/175
