### ISSUE TITLE
Adding An Item Triggers FireFox Native Password Manager

### ISSUE THREAD

**Issue by irrationalagent** [mozilla-lockbox/lockbox-extension#184]
Please delete this issue if we feel that it is not a problem.

When submitting a new credential on nightly mac os, the native firefox login manager asks if you want to save what you just entered in Lockbox. See screenshot below.

<img width="997" alt="screen shot 2017-10-16 at 2 28 57 pm" src="https://user-images.githubusercontent.com/5625313/31638064-d3d57804-b28e-11e7-94df-45a5cb3cb7d5.png">

The only reasons that I can think of that this may be a (minor) issue:

1. The user already has a similar (conflicting?) credential in the Fx native password manager and clicking save changes it / dupes the existing entry.

2. Testers accidentally pollute their native Fx password manager with foobar / test credentials 

Both 1 and 2 of course require the user to actively allow the native PW manager to save the lockbox entry, which I feel is unlikely.

**Comment by linuxwolf** [comment]
This is tricky to fix.

The most expedient is to ask users to uncheck "Remember logins and passwords for websites":
![image](https://user-images.githubusercontent.com/757401/31833006-609f1d2c-b586-11e7-8d85-bead2095992b.png)

As a not-quite-WebExtension, I believe it's possible to modify that pref on install.

**Comment by jimporter** [comment]
Yeah, I'd have thought `autocomplete="off"` would disable the built-in login manager, but nope.

**Comment by sandysage** [comment]
- [ ] Add a note to Release Notes that we're turning off the doorhanger requesting the user to save the password upon install (setting the pref when the extension is installed) but the user can manually  change that pref back
