### ISSUE TITLE
Firefox internal password manager detects lockbox new-entry field as login field

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla-lockbox/lockbox-extension#187]
STR:
1) Open Lockbox
2) Create new Entry
3) Enter a username, password and some other things
4) Firefox's built-in password manager detects the create-form as a login-form

Screenshot:

http://storage7.static.itmages.com/i/17/1017/h_1508235983_1907071_c81712dcca.png

**Comment by m8ttyB** [comment]
@mozfreddyb We genuinely appreciate your eyes on the project, thank you for filling the issue. This appears to be a duplicate of issue #184 

Keep filing bugs.

**Comment by linuxwolf** [comment]
Duplicate of #184
