### ISSUE TITLE
Cannot install directly

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#189]
2 early reports that Nightly wouldn't allow direct install.  Instead these users had to download the XPI and manually install. It was noted that this is potentially a redirection restriction of add-ons.

* jkt reported [via slack](https://mozilla.slack.com/archives/C4LNYNJ8G/p1508206301000058?thread_ts=1508195825.000191&cid=C4LNYNJ8G).
* dietrich reported via email

**Comment by m8ttyB** [comment]
I'm having difficulty reproducing this using a fresh profile. Note I'm using https://github.com/mozilla/ff-tool

**Comment by linuxwolf** [comment]
@sandysage do you have any details on what the steps are?
* Click the link in an email in a dedicated application (e.g., Thunderbird, Mail.app)
* Click the link from webmail (e.g., gmail.com)
* Other?

**Comment by jonathanKingston** [comment]
Click from Gmail in Nightly. The issue I think is Gmails redirection links and how they have a restriction on being an install path to prevent spoofing of installs - that said when I have done this before you can just send the users to a HTML page that then clicks a button on the page with JavaScript so it's not really a good restriction anyway.

**Comment by sandysage** [comment]
To be addressed in #210. This is only an issue with Alpha which we'll handle with a link in our docs.
