### ISSUE TITLE
Documentation is not published

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#197]
The documentation at https://mozilla-lockbox.github.io/lockbox-extension has not been updated for at least two weeks.

**Comment by linuxwolf** [comment]
Now Travis-CI is broken broken.  New PR coming.

**Comment by devinreams** [comment]
Oh shoot. I realize this is may be because I later added the "releases" deploy.

So now now we have "package" run after "doc" which means a full clean happens (including doc clean) meaning no more "site" directory, I believe. 😔

**Comment by linuxwolf** [comment]
That is exactly what's happened.

Changing the order to the following fixes `pages`, but needs to confirm `releases`:
```bash
npm run package
npm run doc
```
Testing is happening on my local fork.

**Comment by devinreams** [comment]
Thanks for continuing to clean up my Travis mistakes.

**Comment by linuxwolf** [comment]
@devinreams  👍 
Now shoo and go back on leave 😸

**Comment by jimporter** [comment]
This is just for the future, but another way to handle deployment is to run `gh-deploy` in Travis: https://github.com/mkdocs/mkdocs-bootswatch/blob/master/.travis.yml#L29-L35

This is probably how we'll do things for multi-versioned docs when we have those.
