### ISSUE TITLE
Static Analysis of accessiblity issues

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#198]

**Comment by devinreams** [comment]
Should we add an a11y plugin or similar? First attempt was made here but abandoned: https://github.com/mozilla-lockbox/lockbox-extension/pull/100

I think it's worth doing this, especially since its easy and should help maintain/increase our quality, right?

**Comment by jimporter** [comment]
The ESLint plugin didn't seem super-useful to me, since it looked like it was only catching highly-obvious problems. @m8ttyB Didn't you say someone was working on this who had some better solutions in mind?

**Comment by m8ttyB** [comment]
I have @kimberlythegeek looking at this right now. We're considering an a11y extension or package Python aXe that extends pypom. Leaning more towards the latter. Timeline for an opinion on PI's side is January 2018.

**Comment by pdehaan** [comment]
Cool, aXe is really good! I use the Firefox/Chrome add-on to do some manual a11y linting, but it really seems to hate linting non-HTTP/S sites, which makes it difficult to work with web extensions.

I also came across https://github.com/reactjs/react-a11y, but haven't tested it locally yet, or seen how it differs from the [**eslint-plugin-jsx-a11y**](http://npm.im/eslint-plugin-jsx-a11y) ESLint plugin (ref #100).

**Comment by m8ttyB** [comment]
+1 @pdehaan we're aware of react-a11y and exploring that as well. Don't really have an opinion on it atm.

**Comment by m8ttyB** [comment]
I'd like to suggest closing this issue, @kimberlythegeek will be working with Yura to create an illustrated test strategy for accessibility. New issues will be opened to track work as we scope the work.

Closing this.
