### ISSUE TITLE
Create telemetry dashboards for Alpha

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#199]
Created re:dash dashboards.

Needs input from team at #273

**Comment by irrationalagent** [comment]
Here's the link to the Re:dash dashboard for lockbox (this is accessible by all moz employees):
https://sql.telemetry.mozilla.org/dashboard/lockbox

There are more things to add here, but it's a good first start. It captures something like DAU, datastore activity, and the startup funnel for new users. I will add more when there's time but for now it should give us a good idea of the basics. It refreshes on its own once a day.

**Comment by devinreams** [comment]
Thanks @irrationalagent. I'll make a note of letting you know when new features or events are live in production so any updates to the dashboard can be accounted for (eg: when #342 is live and we can track the copy button event).
