### ISSUE TITLE
Building dist with webpack

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#20]
so src is actually just source and dist is actual final code

there's a way to do this using webpack

any need to actually add watch or anything? jpm run will do this for us.

**Comment by linuxwolf** [comment]
Adding watchman and a `npm run watch` script automagically builds `dist` (including running `webpack`) whenever something changes in `src/`. I don't know jpm well enough, but will it call out to npm run scripts in the same manner?
