### ISSUE TITLE
Verify the extension updates correctly when a new release is pushed

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#203]
Create a process document for verifying pre-release that an update to a previously installed extension works correctly.

**Comment by m8ttyB** [comment]
This will require a fuller conversation, but what I'd like is a staging instance that parallels our production flows. The extension served up by the staging flow should represent a stable release that includes all work completed for that release at the moment of _pens down_. 

PI will do final verification, including but not limited to, update verification, acceptance testing, etc.

**Comment by devinreams** [comment]
@m8ttyB this is specific to the Test Pilot website (end to end) right?

Because we've seen that extension does update itself in the browser (eg: today with 0.1.1-alpha) right?

**Comment by m8ttyB** [comment]
@devinreams yes, we did see the extension update as well as the integrity of the data was maintained. I would like a mechanism in place to verify that this works prior to releasing to our production env, Testpilot.

**Comment by devinreams** [comment]
>I would like a mechanism in place to verify that this works prior to releasing to our production env, Testpilot.

@m8ttyB Pardon my lack of understanding, do you already have some ideas about how to achieve that?

- I presume @pdehaan and perhaps others from the Test Pilot team are the right folks to see what (if anything) they do to cover off on this?
- Is one of the next steps for you to coordinate with them on this point?
Do you want to do it before our public release in December?

At this point I feel we're fairly covered here as: 

1. we're relying on the cloudops deploy mechanism wired into GitHub and `files.testpilot.com` (the connection, site availability, etc. is out of our control here and handling other experiments)
2. we're relying on Firefox checking the `updates.json` properly and retrieving the files, unpacking, etc.

I'm personally interested in learn more from you all about how you want to test and verify the upgrade process accordingly. 😀

**Comment by m8ttyB** [comment]
@devinreams tl;dr to date, the pattern that I've asked for, creating a pre-prod/canary/staging env that outputs a signed extension, isn't one that other teams use. At this stage I'm comfortable with what our current deployment and testing cycles look like.

Your [comment](https://github.com/mozilla-lockbox/lockbox-extension/issues/203#issuecomment-344383884) is inline with my thinking.

The second portion of the story is validating that once a user updates an extension, unintended consequences don't occur to that user's data. This is covered in our testing as well, but not against a realistic set of data. My thought was to create a staging environment that outputs a stamped, signed release for testing since this would allow us to validate that singular edge case.

**Comment by sandysage** [comment]
After discussing with @m8ttyB we're going to close this as complete given our manual approach to verifying the extension updates works for now. This might be need to be revisited once the extension is released on Test Pilot or when we launch to the wider world.
