### ISSUE TITLE
Search entries

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#204]
When I have several Lockbox entries and I need to access an online account, I need to be able to quickly find an entry by website address, entry name, or username.

# Acceptance Criteria
- Search filtering appears anywhere the list of entries appears
- There is no explicit action to search (more contextual)
- Each character entered in the search field narrows the list of options with each character entered/removed

# Expected behavior
1. Pre-req: assumes you have a Lockbox account created and at least 1 entry saved
2. Navigate to Lockbox by clicking the browser action
3. Default view has full list of entries, by Entry Name, ordered alphabetically
4. Enter a character in the search field
5. The list of options narrows to only include those entries that have an entry name, website address, or username that start with that character
6. The list of options continue to narrow with each additional character to only include those entries that start with those characters
7. Remove character(s) from the search parameters
8. The list of options expand to include all entries that have an entry name, website address, or username that start with the characters provided

# Visual Design
Use Photon design standards for input fields: http://design.firefox.com/photon/components/input-fields.html

# Context
Users have many accounts, often upwards of 100+, and that number continues to grow. We see signs of that being problematic in research and the high prioritization of the problem "Having so many accounts that it's hard to keep track of them all."

Accessing accounts is when efficiency is most required. Ability to search entries is one way to help bring the needed credentials into focus quickly.

# Tasks
- [X] #80

**Comment by sandysage** [comment]
Option: pre-fill search based on context.

**Comment by sandysage** [comment]
@m8ttyB Can you please confirm this flow checks out and is incorporated into our test steps?

**Comment by m8ttyB** [comment]
The acceptance tests are captured in the Search test suite - https://testrail.stage.mozaws.net/index.php?/suites/view/1646

**Comment by devinreams** [comment]
Thanks for confirming, @m8ttyB! 🙇
