### ISSUE TITLE
Save entries

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#205]
When creating a new online account, I want to save the credentials in a secure place _as easily as_ writing them down in a document or notebook, so that later I can recall them without having to remember the credentials.

# Acceptance Criteria
1. Saving a new entry has limited barriers, including having no required fields
2. Navigating away from an entry (eg clicking "home") prompts the user to save

# Expected behavior
1. Pre-req: assumes you have a Lockbox account created
2. Navigate to Lockbox by clicking the browser action
3. Click "New Entry"
4. Enter credentials in fields: entry name, website address, username, password
5. Click "Save"

# Visual Design
TBD

# Context (research, metrics, finding)
Saving credentials is an important part of the account management piece. And the high prioritization of users ranking "having so many accounts that it's hard to keep track of them all" problem statement indicates that saving entries is a part of the larger problem around managing those credentials when they need to be later recalled to access an account.

# Tasks
- [X]  #162

**Comment by sandysage** [comment]
@m8ttyB Can you confirm this workflow checks out and is incorporated into our test steps?

**Comment by m8ttyB** [comment]
Captured, the acceptance tests are in the Password Editor test suite
https://testrail.stage.mozaws.net/index.php?/suites/view/1649

**Comment by sandysage** [comment]
Awesome-sauce! Closing.
