### ISSUE TITLE
View entries in a doorhanger

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#206]
When accessing an online account, I need to be able to reliably log in with my saved credentials. If that does not autofill the form, then I need to be able to copy, and even see, the password to manually enter those details into the website form.

# Acceptance Criteria
1. Viewing an entry details takes 3 clicks or less
2. Viewing all the entries or a single entry doesn't take the user out of focus from the web form
3. Read view of entries is unencumbered by any other action, including "create a new entry"

# Expected behavior
1. Pre-req: assumes you have a Lockbox account created and at least 1 entry saved
2. Navigate to Lockbox by clicking the browser action
3. Default view has full list of entries, by Entry Name, ordered alphabetically
4. Click the entry name to see the entry details
5. Entry details has option to "show" or "copy"
6. Clicking out of the doorhanger, closes it

# Visual Design
https://mozilla.invisionapp.com/share/MHEBCD4PK#/262323598_D_1-1-0_Default_-_Entries_List 

# Context (research, metrics, finding)
Accessing accounts is when efficiency is most required. Research indicates that users might change behavior (consider or take a different action than the default), but not when accessing accounts, sensitive or not.

Prior issue was created here: https://github.com/mozilla-lockbox/lockbox-extension/issues/112

# Relevant user stories

- [x] Implement initial doorhanger code #338
- [x] Add Telemetry events to doorhanger #358

**Comment by sandysage** [comment]
- Prereq: the database is unlocked/signed-in
- Click on the toolbar icon
- List of entries appears in a doorhanger
- Click an entry to see details
- Click edit to open the main editor, in a tab, to that entry in edit mode
- Click add new to open the main editor, in a tab, to a blank new entry
- Click fullscreen to go to the editor, in whatever state it's current at
- Search behaves the same as in the fullscreen editor, just in the doorhanger
- Click Sign out locks the database

![screenshot-2017-10-27 2 1 0 lockbox home popover - returning user - entries list](https://user-images.githubusercontent.com/850418/32126876-3dd6c5e2-bb30-11e7-952f-5b175290572c.png)

**Comment by changecourse** [comment]
@jimporter I just added the visual design to the description above. Would love to get your review/input ahead of implementation. Also designing additional doorhanger states over the next couple of days.

**Comment by jimporter** [comment]
@changecourse This looks good, and it should be enough for me to get started. I'm going to write up a list of all the stuff I can think of that we need implementation-wise so people can discuss/prioritize.

**Comment by devinreams** [comment]
@sandysage @changecourse @m8ttyB Now that #338 is in place (but hidden/disabled for production releases) you can see it for yourself by updating your local repository and running `npm install` and `npm run run`.

It looks to me like _all_ the acceptance criteria as originally defined are met except for:

- Click edit to open the main editor, in a tab, to that entry in edit mode #355 
- Click add new to open the main editor, in a tab, to a blank new entry #354 
- Click Sign out locks the database #149 

Would you like to re-purpose this as an epic and have open tasks/checkboxes for the above? ☝️

**Comment by changecourse** [comment]
That probably makes sense... and we can also add any other design tweaks from the latest to cover additional doorhanger-specific needs.

**Comment by sandysage** [comment]
Removed the acceptance criteria mentioned above to be better handled in their associated stories. This is ready for PI review and close.

**Comment by m8ttyB** [comment]
Moving to PI verified, our test suites take into account the expected behavior and visual design requirements.
