### ISSUE TITLE
Editor input validation

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#207]
When adding or editing new entries, I want to be guided through entering my content (all the form fields) so that I enter meaningful and valuable content that I can later access. If the system is not context-aware, I won't understand why the data is not relevant and will think Lockbox is broken.

# Acceptance Criteria
1. Cannot enter more than 500 char for fields:
   - entry name
   - website address
   - username
   - password
2. Cannot enter more than 10,000 char for field:
   - notes
3. An entry cannot be saved if it exceeds the limit

# Expected behavior
1. Pre-req: assumes you have a Lockbox account created
2. Navigate to Lockbox by clicking the browser action
3. Click "New Entry" or navigate into an existing entry and click "Edit"
4. Enter a long string of text in any of the input fields for:
   - entry name (more than 500 char)
   - website address (more than 500 char)
   - username (more than 500 char)
   - password (more than 500 char)
   - notes (more than 10,000 char)
5. Confirm the entry cannot be saved
6. Once all fields in the entry meet the input requirements, clicking "save" saves the new entry / saves the changes to an existing entry.

# Visual Design
Align to current Photon error validation: http://design.firefox.com/photon/patterns/errors.html

# Context (research, metrics, finding)
Alpha launch brought up the use case where a lot of text entered in the fields breaks the interface (#190). This bug finding is part of the larger considerations for input fields and user expectations (#103). 

# Tasks
- [x] #103 
- [X] #190 
- [x] #236 

_Not handling in this user story and will be addressed as part of error handling_
- [ ] #244 Error handling for maxlength

**Comment by sandysage** [comment]
Right now, if too many characters are entered, the entry is truncated to the max limit

This means the user is not notified the entry is altered. This is considered acceptable for Alpha as long strings of text are considered an edge case. This is not considered acceptable for Beta.

**Comment by changecourse** [comment]
This will be the first use case for error validation, based on the photon standards for styling, available here: http://design.firefox.com/photon/patterns/errors.html 

Happy to mock up for each field, but the general approach for us moving forward in this use case would be to identify the one (or more) field(s) that hit the max, throw an inline error on the field identifying the max character count, and not allowing them to proceed with saving their entry until it is rectified.

**Comment by m8ttyB** [comment]
@sandysage and I spoke yesterday. From a test engineering perspective wrt acceptance testing I look for positive and negative acceptance criteria:
* a list of the positive behaviors or workflows ex. A user hits the save button and their edits are saved. Their history log is updated to reflect the edit so they can view previous edits
* a list of the negative workflow.  ex.  A user makes changes to an item but doesn't save their changes. They should be presented with a warnings xyz, the history log is not updated.

**Comment by changecourse** [comment]
Do we need to map/list all potential flows prior to doing the styling for error handling? 

I guess what I need to know is if this is currently blocked or not, and how to best help moving forward.

**Comment by sandysage** [comment]
Revised the story to better encompass the input validation. The remaining requirement for error handling to be addressed at a later time.
