### ISSUE TITLE
Edit & delete entries

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#208]
When managing my account credentials, I want to be able to edit and even delete existing entries.

# Acceptance Criteria
1. Deleting an entry doesn't remove the data from the data store
2. Previous entry data is retained from the last alteration (not further back than the last iteration)
3. Edit & delete options are available anywhere entry details are accessible
4. Option to edit an entry is clear even if not the prioritized workflow
5. User is notified that the action is successful

# Expected Behavior

## Edit from entry in doorhanger
- Prereq: Lockbox is installed. At least 1 entry is saved.
- Click Lockbox toolbar icon
- If not signed in, log into account. Upon login, full screen editor opens in a new tab
- If signed in, doorhanger appears with list of entries
- Click an entry
- Click edit entry
- Editor opens (or focus changes to an already opened editor) in a new tab to the edit view of that entry
- Change any details in the entry from entry name, website address, username, password, notes
- Click "save"
- Confirmation appears
- Close out of the editor
- Recall the entry
- The entry is updated with all the saved edits

## Edit via fullscreen selection
- Prereq: Lockbox is installed. At least 1 entry is saved.
- Click Lockbox toolbar icon
- If not signed in, log into account. Upon login, full screen editor opens in a new tab
- If signed in, doorhanger appears with list of entries
- Click fullscreen
- Editor opens (or focus changes to an already opened editor to the state that editor already exists) in a new tab to the default view with the list of entries.
- Click the entry to edit
- Click "edit entry"
- Change any details in the entry from entry name, website address, username, password, notes
- Click "save"
- Confirmation appears
- Close out of the editor
- Recall the entry
- The entry is updated with all the saved edits

## Delete
- Access Lockbox entry in edit mode (steps above)
- Click "delete entry"
- "Are you sure you want to delete this entry?" warning appears
- Click "delete entry"
- Confirmation appears
- Entry is no longer in the list of entries

# Visual Design

https://mozilla.invisionapp.com/share/5JDP20NYB#/screens
![screenshot-2017-11-1 2 1 1 lockbox home popover - entry detail](https://user-images.githubusercontent.com/850418/32286089-f9f5e798-bef1-11e7-81bb-4953cfee3f89.png)

![screenshot-2017-11-1 1 0 3 lockbox home - entry detail - edit entry](https://user-images.githubusercontent.com/850418/32286153-29774e6c-bef2-11e7-9412-a58fec3f8bcf.png)

# Context
Managing credentials, after the details are saved, is a rare occurrence, and likely triggered by some other external factor. It's not a primary use case, but it needs to be available and easy to access when changes are needed. 

# Tasks
-  ~#280~

**Comment by devinreams** [comment]
This is done so @sandysage is proposing to close this.

One last remaining todo to spin out separately is at #280 which we can put on the backlog.

@m8ttyB is this already captured as part of your end-to-end testing? if not, can we add it please? 😁

**Comment by m8ttyB** [comment]
@devinreams, yes, these test cases are captured in the Password Editor test suite https://testrail.stage.mozaws.net/index.php?/suites/view/1649

**Comment by devinreams** [comment]
>these test cases are captured in the Password Editor test suite

Ah yes, I see them now under "Editor Acceptance Criteria". Wonderful. Thank you. ✅
