### ISSUE TITLE
Landing page to install extension

### ISSUE THREAD

**Issue by hmcgaw** [mozilla-lockbox/lockbox-extension#210]
Create a landing page with link to Alpha extension to use in test.

Example of what’s needed: 
1. http://pageshot.dev.mozaws.net/homepage/install-test-local.html
2. https://moz-activity-streams.s3.amazonaws.com/dist/latest.html
    
@changecourse to provide mockup

**Comment by hmcgaw** [comment]
Title: Lockbox Extension
H1: Click on the link below to installs the Lockbox extensions.
Button label: Install

**Comment by linuxwolf** [comment]
The location can be in our [docs](../tree/master/docs), which are rendered to https://mozilla-lockbox.github.io/lockbox-extension/.

**Comment by changecourse** [comment]
![landing](https://user-images.githubusercontent.com/6164801/31792108-1ebbccec-b4d8-11e7-9f19-3d40d2c2974d.png)


@hmcgaw this work?

**Comment by sandysage** [comment]
Does this need any of [these instructions](https://docs.google.com/document/d/13czBuotckDrIRUrTwgEpv2ezjenJBvdzo9-PHnMpBfI/edit#heading=h.wh7s53mjty5g)?

**Comment by hmcgaw** [comment]
@changecourse that works!

@sandysage nope, the instructions will be in the usertesting.com modal that participants interact with.

**Comment by linuxwolf** [comment]
Here is what it'll look like once PR #228 (once merged to `master`) realizes the landing page as:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/757401/31842722-b8e9da78-b5ac-11e7-8a60-ea98bbade044.png">
