### ISSUE TITLE
Avoid other password manager prompts

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#211]
When accessing Lockbox, I want to save my credentials in one location and I don't want to be prompted by the browser to also save my password.

# Acceptance Criteria
1. The Firefox doorhanger that requests the user to "save the password" is disabled upon Lockbox install (the pref in about:preferences#privacy to uncheck the "Remember logins and passwords for websites" setting)
2. User can manually change the pref back to allow the browser to remember logins
3. Upon uninstall, the pref is changed to remember logins and passwords.

Note: Uninstalling Lockbox changes the pref to remember logins, irregardless of what the setting was before Lockbox was installed.

# Expected behavior

## Install
1. Install Lockbox extension
2. Navigate to about:preferences#privacy in the URL
3. The "Remember logins and passwords for websites" setting is unchecked
4. Add entries to Lockbox, and the browser does not prompt to also save those entries

## Uninstall
1. Uninstall Lockbox
6. Navigate to about:preferences#privacy in the URL
7. The "Remember logins and passwords for websites" setting is checked

# Visual Design
N/A

# Context
Having the browser prompt to save a Lockbox entry is confusing. Early feedback from research, using the Alpha prototype, confirmed that users did in fact seem to be confused by this behavior.

# Tasks

- [X] #184 
- [X] #230

**Comment by sandysage** [comment]
@m8ttyB Can you confirm this flow checks out and is incorporated in our test steps?

**Comment by m8ttyB** [comment]
Captured, this is part of the Smoke Tests Suite - https://testrail.stage.mozaws.net/index.php?/suites/view/1704&

**Comment by sandysage** [comment]
Great. Closing this as 'done'. 

https://gph.is/1ISH9g1
