### ISSUE TITLE
Localize page titles

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#225]
Right now, the page titles for all our documents are unlocalized, and I'm not sure how to localize them via `fluent-react`.

@stasm What's the best way to localize the page title with `fluent-react`? The title element is "outside" of our React code, so `<Localized/>` and `withLocalization` probably won't help.

**Comment by stasm** [comment]
Great question.  I don't have a canonical answer but I'm open to discussing the best practice.

The imperative way would be to set the title in a `componentDidMount` using `getString` (passed by `withLocalization`). This sounds fairly easy to integrate into the existing codebase but has the drawback of being unresponsive to language changes unless more logic is added.

I know some people use [react-document-title](https://github.com/gaearon/react-document-title) to set the title in a declarative manner. It looks like its `DocumentTitle` could be wrapped in a `Localized` but I haven't tried it yet. I'll give it a shot.

Lastly, with React 16, would it be possible to set the title using a Portal?

**Comment by jimporter** [comment]
@stasm `react-document-title` works great, thanks!

**Comment by stasm** [comment]
Great to hear. I documented it at https://github.com/projectfluent/fluent.js/wiki/Localized.
