### ISSUE TITLE
What are privacy vulnerable users' experience and understanding of using Lockbox Alpha?

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#234]
Lockbox Alpha is the scaffolding for Firefox’s new password manager. It is a signed Firefox extension where users can:

* Create a Lockbox account with a master password to lock/unlock your data
* View entries 
* Search entries
* Add, edit, and delete entries
* Submit feedback

We want to uncover:

* Can participants discover their way through using these features?
* Do the features match their expectations?
* What issues are they having?
* How do people react? Positives? Negatives?
* Do participants understand what a the Lockbox master password is?

## Action Items

- [X] Create research plan (objective, research questions)
- [X] Share research plan with team
- [X] Make any necessary changes to objective and/or research questions
- [X] Write [research protocol](https://docs.google.com/document/d/1RvntQacZ_uIUHJ915eOfg_Ayhj7TeVtuR4esnKEB4YI/edit#heading=h.im3z665a934p)
- [X] Create study in Usertesting.com
- [X] Review protocol with team
- [X] Make any necessary changes to protocol
- [x] Run pilot sessions (2)
- [x] Review pilots and make any changes to protocol
- [x] Run study
- [x] Analysis and report
- [x] Share findings with team
- [x] Identify next steps

**Comment by hmcgaw** [comment]
Link to research protocol: https://docs.google.com/document/d/1RvntQacZ_uIUHJ915eOfg_Ayhj7TeVtuR4esnKEB4YI/edit#

**Comment by hmcgaw** [comment]
Link to findings: https://docs.google.com/presentation/d/1fQITBbRjIEgGahK1jIcTGH7IyYdZukv5SzytyiZikso
