### ISSUE TITLE
Evaluate options for form autofill & form save

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#241]
1. Filing website form fields with saved entries in Lockbox
2. Saving form field entries into Lockbox

# Questions

1. What options exist today?
2. Do we achieve any 'quick wins' by leveraging what already exists in Firefox?
3. What do we need to have this functionality in other browsers as well?
4. Assuming this is a significant effort, no matter what option is selected, are there incremental paths forward?

**Comment by sandysage** [comment]
# Retrieve
* contextual menu (choose "fill" on a form)
* fx login manager functionality (not an option)

# Capture
* form capture (arms race)
* doorhanger "add" option to get context - page title and origin

@devinreams to add more information with pros & cons

**Comment by m8ttyB** [comment]
Captured a placeholder in TestRail for testcase ideation, [Autofill and Form Save](https://testrail.stage.mozaws.net/index.php?/suites/view/1738) test suite.

**Comment by devinreams** [comment]
@jimporter @linuxwolf I'm drafting a private doc to explore the various approaches we've discussed to-date. Take a look here and please fill in everything you can and I'll do the same:

https://docs.google.com/spreadsheets/d/1-yCMFvg7z2wQ2G4D5xJRYQ5WPI4LvDDANlBYKOcYQe8/edit#gid=0

**Comment by devinreams** [comment]
Evaluation provided and discussed with research and UX. Thanks @linuxwolf and @jimporter for all your input and @hmcgaw @sandysage @changecourse for the good questions and discussion.

Throwing this back to @sandysage to remember to follow-up here and elsewhere accordingly.

**Comment by sandysage** [comment]
Our plan is a progressive path that starts with:

1. making it easier to copy from the doorhanger ( @changecourse is helping to define that. New issue to come) -> MVP acceptance criteria
2. right click to fill form (contextMenu) from the page + some amount of guidance from the doorhanger -> fast follow post-MVP launch (1st or 2nd sprint)
3. "add entry" button to click that is prefilled with data in page -> fast follow post-MVP launch (2nd or 3rd sprint)
4. port existing Login Manager form detection to Web Extension -> Q1 objective
5. a common framework, ideally as a web-extension that can get auto-installed by other dependent web-extensions, that provides the core detection logic and has the hooks for other web-extensions -> the 1-day dream

The context and prioritization is better outlined and detailed in the doc @devinreams shared.

**Comment by sandysage** [comment]
With regards to MVP and making it easier to copy from the door hanger, we now have todos to support that criteria, including:

- #316 
- #317 
- #313 
- #314 

I'm closing this task as complete with options reviewed, documented, and decisions made for moving forward.
