### ISSUE TITLE
Photon Typography

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#255]
In lieu of extensions.css not providing us the Photon style for free, we can begin implementing our our visual design to align with Photon.

One such area is Typography, and we can begin by adding Fira: https://mozilla.github.io/Fira/ 

My thought is that we can do one foundational effort around the implementation of the fonts, and then a subsequent pass on different weights for specific areas. 

Fonts used thus far: ExtraLight, Light, Regular, Medium, Bold

**Comment by changecourse** [comment]
We can do an additional issue in the future to highlight key component definitions for typography on a 'per component' basis.

**Comment by jimporter** [comment]
The spec says we use different fonts on different platforms. Shouldn't we follow that? http://design.firefox.com/photon/visuals/typography.html

Fira is for "web" stuff, and while we're all HTML, our add-on isn't really a part of the World Wide Web...

**Comment by jimporter** [comment]
We *should* probably use Fira Sans Mono though, since it's an actually-good monospace font that distinguishes similar glyphs. This will make life easier on people when they need to manually type in a password.

**Comment by changecourse** [comment]
Following up on this... and after some back n' forth with some of the designers tied to the Photon effort, it looks like you are right @jimporter, we should use system-based fonts (Segoe, SF, etc) for the extension, as identified in the brand guidelines list above. Looks like Fira will be more tied to other efforts around marketing, as well as the monospace need you had mentioned for passwords.

**Comment by changecourse** [comment]
@jimporter that being said, we may also want to default our monospace to the platform defaults (Consolas and Menlo) instead of Fira's monospace for performance reasons perhaps?

**Comment by jimporter** [comment]
@changecourse I'd strongly recommend against using system defaults for the monospace font. Many monospace fonts just aren't very good for our purposes, and I think we want to provide some guarantees that our monospace font is as readable as possible. In particular, Windows defaults to Consolas, which has precious little different between `1` and `l` (that's number one and lower-case L). Since users may occasionally have to manually type in passwords, we should make sure that it's easy to distinguish each character.

**Comment by changecourse** [comment]
good to know, thanks!

**Comment by changecourse** [comment]
Latest need as I see it:

- [ ] Use of SF Text on Mac instances of Lockbox
- [ ] Use of Segoe UI on Windows instances of Lockbox
- [ ] Use of Ubuntu on Linux instances of Lockbox
- [ ] User of Fira monospace for passwords throughout all instances (?)

I've based all of the latest designs on using the Mac typography styles set in the Photon style guide

<img width="745" alt="screen shot 2017-11-06 at 12 29 27 pm" src="https://user-images.githubusercontent.com/6164801/32459931-5ef14660-c2ee-11e7-84d1-14078276ef36.png">

**Comment by devinreams** [comment]
@jimporter have you already given this some more thought on how precisely to implement some changes, what they all are, etc. (or started on it) or is this something I can pick up and start some work on?

**Comment by jimporter** [comment]
@devinreams This is going to be a bit complicated, mainly because I'd really like to refactor some of the common CSS first. We're getting into way too much copy-paste.

**Comment by devinreams** [comment]
> I'd really like to refactor some of the common CSS first. We're getting into way too much copy-paste.

Sweet, have at it. 👌 I can always come back after you've done that and tweak sizes, colors, etc. once you have it organized the way you want. 

If not already planning on it, I'm sure you are, please double check #300 and #295 landed so we don't diverge and get too much going on in parallel. 😁

**Comment by devinreams** [comment]
Quick notes from discussion and #295 before I forget:

- we may be getting system fonts "for free" from Firefox? to confirm
- Padding between field label and field needs to be increased on welcome screen (but could be addressed with the typography story instead) 
- overall font sizes on Welcome screen could be re-reviewed and made consistent
- Text selection color (we don't allow selection)
- Form fields in Create a New entry are indented and shouldn't be (margin-inline-start: 7px;)
- Show/Hide field vs. SVG iconography: "FxA already uses a "show" string, and I think it'd be nice if we could remain consistent."
