### ISSUE TITLE
e2e tests -  update travis config to run smoke tests

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#259]
Update the `.travis.yaml` to execute the smoke test suite.
* Tests configured to run in headless mode.
* Tests configured to execute in parallel.

**Comment by jrbenny35** [comment]
I am thinking about using a docker image of selenium and firefox, as this would be less maintenance for when geckodriver updates. It would also mean the devs wouldn't need to install geckodriver. Thoughts?

**Comment by m8ttyB** [comment]
@jrbenny35 and I chatted about this today. As a thought experiment, it does sound tidy. `--cache-from` might be a path forward for this. That said, the overhead for setting up a dev env is minimal, requiring installing Geckodriver and adding it to the classpath. Let's de-scope this work until after we've stabilized a the test runs.
