### ISSUE TITLE
Distribute Alpha extension on desktop

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#26]
- [x] package script to build xpi
- [x] added to internal sign-xpi Jenkins pipeline (via Test Pilot and CloudOps)
- [x] confirmed signed properly
- [x] confirmed updates distributed
- [x] process documented
- [x] write 0.1.0-alpha changelog #76 #176 
- [x] publish 0.1.0-alpha tag and release on GitHub

**Comment by devinreams** [comment]
Thinking about how to package, sign, and distribute this over at #62

**Comment by sandysage** [comment]
Completed 10/16
