### ISSUE TITLE
Locked popover does not auto-focus on password field

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#260]
Current behavior: click the browse action icon, popup opens prompting for password,  I have to click (or tab) to the field to enter the password

Proposed behavior: when popup opens, autofocus on the password field so I can just start typing

**Comment by jimporter** [comment]
Works for me. You're probably hitting https://bugzilla.mozilla.org/show_bug.cgi?id=1324255

**Comment by devinreams** [comment]
Ah well, this is happening inconsistently for me. 

I just opened it now and the input was in focus, as expected, somehow.

Closing for now as this may not be the long term "unlock" experience anyway. We can re-open and revisit if still an issue as we work on the popup more...

**Comment by jimporter** [comment]
Per the bug I linked, it's a race condition in Firefox that has a patch, so I don't think we need to worry about it too much.
