### ISSUE TITLE
e2e tests - is there an impact on telemetry?

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#263]
The automated test suites will be running frequently. What are the impacts to gathering telemetry data, if so, how do we mitigate it?

**Comment by jimporter** [comment]
Probably just do something like we already do with local builds: https://github.com/mozilla-lockbox/lockbox-extension/blob/master/jpm-prefs.json

**Comment by davehunt** [comment]
If using Selenium with GeckoDriver and Marionette, then this is already taken care of. See https://dxr.mozilla.org/mozilla-central/rev/1c618b1a13662de7cec429f606367db3827b6dc7/testing/marionette/server.js#55-293 and https://dxr.mozilla.org/mozilla-central/rev/1c618b1a13662de7cec429f606367db3827b6dc7/testing/geckodriver/src/prefs.rs#238 for details.

**Comment by m8ttyB** [comment]
Thanks @davehunt, spot on. Closing this issue given that it is already covered for us.

/cc @jrbenny35
