### ISSUE TITLE
Photon button styles

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#265]
http://design.firefox.com/photon/components/buttons.html

**Comment by pdehaan** [comment]
I also came across https://github.com/FirefoxUX/design-tokens/tree/master/colors the other day which has a bunch of Photon color variables.

**Comment by changecourse** [comment]
@jimporter I'm using puffy and default versions of both the primary and secondary styles for button states, which can be seen here: https://mozilla.invisionapp.com/share/MHEBCD4PK#/262028743_1-0-0_Lockbox_Home_-_No_Entries 

The above style guide link doesn't handle things like disabled state, but we can chat through best approach as needed. (I dialed back opacity to 50% in latest designs for now)

Let me know if you'd like to discuss further depending on where you're already at with this issue.
