### ISSUE TITLE
OpenYOLO support 

### ISSUE THREAD

**Issue by mhalano** [mozilla-lockbox/lockbox-extension#267]
Would be nice integrate Lockbox with OpenYOLO so people can access passwords on mobile and computer syncing with Firefox Sync.

**Comment by devinreams** [comment]
Thanks @mhalano, we're definitely thinking about this and our product team has spoke with the OpenYOLO product folks.

Closing this to move to the Android repo for future consideration: https://github.com/mozilla-lockbox/lockbox-android/issues/2
