### ISSUE TITLE
Client Environment Variables to Include in Re:Dash Dataset

### ISSUE THREAD

**Issue by irrationalagent** [mozilla-lockbox/lockbox-extension#273]
I'm looking into creating a custom lockbox dataset to be available in re:dash so that we all have easy access to once-daily updated lockbox data. 

Our event data takes a ride on the main ping which also includes other data about the user's environment, OS, other add-ons that are present, etc. It would be easy to include some of this other data in our re:dash dataset, if anyone believes it would be useful to have - e.g. if you have concerns about certain platforms, architectures, browser versions etc. 

There is a slight trade-off to adding more data, as the s3 job to wrangle the data will be slightly longer for each additional variable, as will our sql queries. So I would counsel not to include everything just for the heck of it. 

The full list of variables that we have access to is here: 

https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/environment.html

Note that (in theory) some users have data collection for certain things turned off. 

Please leave a comment in this issue with variables you'd like to see included and I'll add them to the list. **Please try to make your requests by the end of thu 11.2** I am looking to have the final dataset ready for the data engineers to import to re:dash by the start of next week.

**Comment by devinreams** [comment]
Some ideas come to mind:

- Firefox and O/S versions (if not already part of the ping, wasn't clear to me at a glance)
- default browser (so we can infer if this is someone's primary browser)
- locale (so we know what languages to focus on, ideally we cover the same as Firefox itself)

I also think it'd be nice to identify other identity/password manager addon IDs and see if users are also using those, but realize that may be asking a lot (and should perhaps be opt-in).

**Comment by irrationalagent** [comment]
> I also think it'd be nice to identify other identity/password manager addon IDs and see if users are also using those, but realize that may be asking a lot (and should perhaps be opt-in).

Re: whether add-on tracking needs to be opt-in.... since this is opt-out info that is already collected by telemetry and people have already agreed (at least implicitly) to have it collected, I'm not sure that we have to ask a second time to use it. I'll ask Rebecca just in case.

**Comment by linuxwolf** [comment]
I don't see this explicitly in the client environment variables, but is it possible to also get the "browser uptime", meaning the amount of time since the browser session was started?

**Comment by irrationalagent** [comment]
Yes, I believe so. I'll add it.

**Comment by sandysage** [comment]
If worth the effort, we might want to consider evaluating user prefs BEFORE installing Lockbox. Particularly the saved logins setting. This might give us some limited insight around user trust of storing passwords in the browser.

**Comment by linuxwolf** [comment]
I think we can do that, but would require some code changes; record a telemetry at the moment of installation, before the pref is checked and changed.
