### ISSUE TITLE
Use greenkeeper to help keep up dependencies (mostly automating dependency updates)

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#276]
[Greenkeeper](https://greenkeeper.io/) is a service that will monitor the `dependencies` and `devDependencies` of a Javascript project, and submit pull requests when things are updated -- relying on any build/test hooks (aka Travis-CI) to verify code is still compatible.

This service removes some of the burden on tracking dependencies, and is free to open source projects

## To Do
* [x] merge `master` into branch `greenkeeper/initial`
* [ ] review changes and ensure clean build (CI/codecoverage/etc)
* [ ] merge PR into `master`

**Comment by devinreams** [comment]
I like this idea. 👍 

And Greenkeeper just got added to [GitHub Marketplace](https://github.com/marketplace/greenkeeper) so it's just one-click to integrate.

I'll try it out here real quick and see how the automagic PR creation looks so we can review it together and see how we like it...

**Comment by devinreams** [comment]
Initial PRs opened:

- https://github.com/mozilla-lockbox/lockbox-datastore/pull/54
- https://github.com/mozilla-lockbox/lockbox-extension/pull/304
