### ISSUE TITLE
Write unit tests that run locally with: mocha, chai, assert

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#28]
Things we need to test:

* [ ] `bootstrap.js`
* `webextension/`
  * [x] `common.js`
  * `background/`
    * [x] `datastore.js`
    * [ ] `index.js`
    * [x] `messagePorts.js`
  * `manage/`
    * `components/`
      * [x] `app.js`
      * [x] `item.js`
      * [x] `itemDetails.js`
      * [x] `itemList.js`
    * `containers/`
      * [x] `addItem.js`
      * [x] `allItems.js`
      * [x] `currentItem.js`
    * [x] `actions.js`
    * [ ] `index.js`
    * [ ] `l10n.js`
    * [x] `reducers.js`

**Comment by devinreams** [comment]
@jimporter after chatting with @m8ttyB yesterday, it sounded like you were going to help review and finish up this branch:

https://github.com/m8ttyb/lockbox-extension/tree/chai_goodness

Is that right? I want to be explicit about who owns the final work to get tests running against the current extension code.

**Comment by jimporter** [comment]
Reopening this to cover the remaining tests; we're only at 35% coverage at the moment! I'll update the original comment with a list of the main remaining tasks.

**Comment by devinreams** [comment]
@jimporter @m8ttyB based on the coverage and description in #58 I'm going to set this issue to close once that PR merges. ✅ ✅
