### ISSUE TITLE
Reduce confusion from "entries" terminology where possible in the visual design

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#281]
When creating a new Lockbox item/entry, I don't want to be confused by what an entry is to create, edit, or delete one. With the field not having context, it's possible multiple creations would result in a long list of "no entry name" entries that doesn't indicate the origin / website.

# Acceptance Criteria
- The actions of adding, editing, or deleting an entry aren't focused on the label "entry.
- Visual design supports adding, editing, and deletion functions without the use of the term "entry"
- The "entry" term is appropriate for secondary, and support information or details.

# Expected behavior
TBD

# Visual Design
## Doorhanger
https://user-images.githubusercontent.com/850418/32669560-3233c428-c5fe-11e7-84b8-f8fd996a7193.png

## Full editor
TBD

# Context
In research with users engaging Alpha, the Entry Name field was confusing to some participants, and thus was not actively entered. This could be a blocker to use if users do not populate this field and then later become disoriented by the seeming lack of organization to the list (eg a lot of entries with "no entry name").

# Tasks
- [ ] Update the UX to remove "entries" entirely (eg "New Entry" becomes "Add New") OR if a term is needed (eg "X # of entries) a more accurate label is established with the content team

**Comment by jimporter** [comment]
Aren't we putting the cart before the horse here? Like a lot of things in the current version, the primary workflows that we've discussed for user interaction don't exist yet (i.e. auto-populating the datastore), so right now, we're looking at the stuff that *does* exist, but should be a pretty uncommon way of entering data. I expect that when we have all the UI we want, manually entering new entries will be reserved for things like storing non-web passwords.

**Comment by linuxwolf** [comment]
Some questions:

* If a website address is not included for some reason, what summary should be displayed?
* What are the accessibility considerations, if any?

**Comment by sandysage** [comment]
Confusion around "entry" is addressed in the new design for the mini-editor view:
![screenshot-2017-11-10 d 1 1 0 default - entries list](https://user-images.githubusercontent.com/850418/32669560-3233c428-c5fe-11e7-84b8-f8fd996a7193.png)

These adjustments also need to be considered in the full editor view as well. For instance, does this need to read "New Entry" or can the editor also have the same iconography + to signal the same action there?

Additional considerations need to be made for 'first run' with the first call to action as "create a new entry". Do we provide enough context around what an 'entry' is?

From there, I think there is consideration of populating those fields from the URI, mitigating the opportunities for both the 'Name' and 'Website address' to be empty.

**Comment by sandysage** [comment]
Updated this issue to remove all references to URI detection. Let's have this task for the visual & content changes to help reduce the confusion of "entries".

**Comment by sandysage** [comment]
Closing this as complete.
