### ISSUE TITLE
ReferenceError: reference to undefined property "error"

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#283]
Running the latest code from master (1ec24a358d01787ee61c66e4bf56e627c30605eb) in Nightly and spotted this error in my console:

> _ReferenceError: reference to undefined property "error"_
> &mdash; via [master-password-setup.js:74](https://github.com/mozilla-lockbox/lockbox-extension/blob/9f732e7161d011ac5111a75ed45b563e7fa5f23f/src/webextension/firstrun/components/master-password-setup.js#L74)

https://github.com/mozilla-lockbox/lockbox-extension/blob/9f732e7161d011ac5111a75ed45b563e7fa5f23f/src/webextension/firstrun/components/master-password-setup.js#L74

**Comment by devinreams** [comment]
@pdehaan To help narrow down when this was introduced, can you recall a point-in-time this _wasn't_ happening? We could then use git-bisect to find the culprit.

Unless this immediately rings any bells for @jimporter or @linuxwolf.

**Comment by jimporter** [comment]
Is this causing an actual problem, or is it just random error spew? We get lots of reference errors that I think are the result of babel doing various browser polyfills for the fancy syntax we use.

**Comment by pdehaan** [comment]
I don't recall when this was introduced. Not sure if I've been trolling through the dev console logs before now.
I also don't think it was breaking anything or causing any issues. But it was the only warning I spotted that wasn't coming from DevTools or babel/webpack.

Looks like it was introduced in https://github.com/mozilla-lockbox/lockbox-extension/commit/c118f9e4922b79c7bfcd258d3400a7fc05d55589. I _assume_ it only appears because there is no `error` prop in `this.state` when we destructure.

**Comment by devinreams** [comment]
@pdehaan I ran through a fresh profile and don't see any stray errors. Are you seeing this still?

Either way, #209 will remove/replace the "master password". I'm closing this as stale and soon-to-be superseded but please feel free to re-open if you spot something we missed.
