### ISSUE TITLE
"undefined" class names in toolbar spacer

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#288]
<img width="1116" alt="lockbox_entries" src="https://user-images.githubusercontent.com/557895/32390574-2a1d8bf6-c08c-11e7-83e7-e35e1587204d.png">

After a bit of digging, I think it's because we're not passing a `className` to the `<ToolbarSpace/>` components in:

https://github.com/mozilla-lockbox/lockbox-extension/blob/6aa034a9207f2772862a6f65b5fb76f9d515b353/src/webextension/manage/components/app.js#L27-L31

https://github.com/mozilla-lockbox/lockbox-extension/blob/6aa034a9207f2772862a6f65b5fb76f9d515b353/src/webextension/manage/components/app.js#L32-L36

But in [/src/webextension/widgets/toolbar.js:24-29](https://github.com/mozilla-lockbox/lockbox-extension/blob/6aa034a9207f2772862a6f65b5fb76f9d515b353/src/webextension/widgets/toolbar.js#L24-L29) the undefined `className` gets set to the literal string `undefined`:

https://github.com/mozilla-lockbox/lockbox-extension/blob/6aa034a9207f2772862a6f65b5fb76f9d515b353/src/webextension/widgets/toolbar.js#L24-L29

Doesn't seem to break anything, but feels weird. Not sure if we should default the passed `className` argument to an empty string, or just do something like:

```js
`${styles.toolbarSpace} ${className || ''}`.trimRight()
```

---

```diff
diff --git a/src/webextension/widgets/toolbar.js b/src/webextension/widgets/toolbar.js
index 81403df..27545fc 100644
--- a/src/webextension/widgets/toolbar.js
+++ b/src/webextension/widgets/toolbar.js
@@ -8,7 +8,7 @@ import React from "react";
 import styles from "./toolbar.css";

 export default function Toolbar({className, children}) {
-  const finalClassName = `${styles.toolbar} ${className}`.trimRight();
+  const finalClassName = `${styles.toolbar} ${className || ''}`.trimRight();
   return (
     <menu className={finalClassName}>
       {children}
@@ -22,7 +22,7 @@ Toolbar.propTypes = {
 };

 export function ToolbarSpace({className}) {
-  const finalClassName = `${styles.toolbarSpace} ${className}`.trimRight();
+  const finalClassName = `${styles.toolbarSpace} ${className || ''}`.trimRight();
   return (
     <span className={finalClassName}/>
   );
```

**Comment by jimporter** [comment]
Ya, that's a bug. We generally use `defaultProps` for this though. I'll make a patch.

**Comment by jimporter** [comment]
@pdehaan Ok, fixed with a test. Thanks for filing this!

**Comment by pdehaan** [comment]
Cool, thanks. Not sure if we want to fix **/src/webextension/widgets/text-area.js** to use `defaultProps` while we're at it:

https://github.com/mozilla-lockbox/lockbox-extension/blob/6aa034a9207f2772862a6f65b5fb76f9d515b353/src/webextension/widgets/text-area.js#L29-L30
