### ISSUE TITLE
Add python dependency updater.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla-lockbox/lockbox-extension#291]
It would be nice to keep the Integration tests dependencies updated. We usually use https://github.com/pyupio/pyup and it will add commits on my behalf (if I am the person who sets it up), when new versions of the dependencies are updated.

See this PR as an example: https://github.com/mozilla/FoxPuppet/pull/128

**Comment by jrbenny35** [comment]
I think I need to be added as an admin or whatever github calls it.

**Comment by devinreams** [comment]
@jrbenny35 To be clear, pyup would be responsible for all the dependencies for tox, selenium, etc.?

We're also considering our node/JS dependency management at #276 #304 so I'm curious what @jimporter and @linuxwolf think about introducing more here...

**Comment by m8ttyB** [comment]
@jrbenny35 makes a good suggestion, pyup is a tool that the PI team has adopted for dependency management across all of our Python based testing flows. 

It can become a bit noisy as Python packages are updated, but it can be tuned to only provide PRs with updates based off our preferences. Such as security updates, etc.

Worth discussing.

**Comment by devinreams** [comment]
>@jrbenny35 makes a good suggestion

Totally agreed. I should have said that first. 🥇 

Here's what the `--initial` branch/pull request looks like: https://github.com/mozilla-lockbox/lockbox-extension/pull/367

**Comment by devinreams** [comment]
@jrbenny35 if you grab a personal access token from https://github.com/settings/tokens and run pyup on this repo does it successfully open a PR for you?

I figure this would be something worth you trying (making sure it creates a branch and PR for you). Aaaand because I think I broke my python environment locally so can't re-run this myself right now. 😫

**Comment by jrbenny35** [comment]
@devinreams I don't think this is working anymore. Maybe you could look into it since you did set it up.

**Comment by devinreams** [comment]
You're right. It looks like I disconnected the pyup.io service when it got noisy when attempting to get the first update completed and never re-enabled it.

I will enable it now and see what it finds/does and review it with the team. Either way, it seems the behavior is similar to greenkeeper which we're using here so it should be automagic and familiar...

**Comment by jrbenny35** [comment]
@devinreams you can also set it to just update once a week to cut down on the noise. We do that on addons-frontend and it works great.

**Comment by devinreams** [comment]
OK initial config is set to update (all dependecies) weekly: #586

First set of dependency update PRs were opened: #592 #591 #590 #589 #588 #587
