### ISSUE TITLE
Update first-run editor

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#292]
When I first download the extension, I want to understand (or be reminded) of the purpose of Lockbox, in support of the first action: create the first entry.

**NOTE** This first entry is decoupled from creating an online account. It's a manual initial set-up, which is the end-result of the onboarding experience.

**NOTE** As explored in #209, securing a Lockbox is not a requirement for first run, in an attempt to allow users to get value prior to needing an account. This first run screen is the opportunity to explore what that value message needs to be to support creating a first entry.

# Acceptance criteria
1. It should have onboarding and support instructions to guide users through first time use
2. It should provide easy-to-find access to additional information
 
# Expected behavior
1. Upon download, a user sees the "0 entry screen" or first run experience as outlined in the visual design (below).
2. Creating a first entry is the primary call to action.
3. After the first entry is created, the user is guided to secure the account with a Firefox account.
4. There is persistent access to the "FAQ" via a navigation bar that links out to an external site with the FAQ details.

# Visual design
![screenshot-2017-12-6 lockbox fx add-on preview mode - invision](https://user-images.githubusercontent.com/850418/33678021-daccb4cc-da77-11e7-80cd-6a3d5eb1ffd9.png)

# Context
In Alpha research, we discovered that the value and purpose of Lockbox needs to be more clearly communicated. This first run screen is where we can reinforce, and highlight, the message that prompted the Lockbox download.

# Tasks

*This relies upon FxA landing (#209) first.*
- [x] #209
- [X] Content strategy for first-run message
- [x] Updated Text
- [x] #331 
- [x] decision on "Already Using Lockbox? Sign in.."

**Comment by m8ttyB** [comment]
Once additional context and design land for this, I'll add acceptance tests to the[ First Run Scenarios test suite](https://testrail.stage.mozaws.net/index.php?/suites/view/1619).

**Comment by changecourse** [comment]
@sandysage The latest visual designs represent the goals stated, but do we need to add additional tasks for both the removal of the master password? 

I think the current flow accounts for our needs, but this issue (+/- any additional issues) may need to be updated to reflect all of the following changes:

- Removal of need for master password creation
- Rework of initial landing page to include primary navigation and sidebar
- Upon successful installation of extension, an automatic launch of the lockbox tab (this may already function this way, but I'm not sure how to test that behavior on my end)

**Comment by devinreams** [comment]
May need to be reconciled with #293 and then one closed?

**Comment by sandysage** [comment]
Closing #293 as duplicate.

**Comment by devinreams** [comment]
@sandysage @changecourse This is where we'd like to gather up all the changes to the landing page (homepage) and first run experience, right?

If so, based on our recent conversations, I think this is back to `needs-ux` until we're final-final on what you want to change, right?

**Comment by devinreams** [comment]
Updates reflected in the original description include the fact this relies on #209 ("pre-run master password" swapped out for "FxA auth post-run")

As of today, this is what the design for the landing page looks like:

<img width="1072" alt="1_0_0_lockbox_home_-_welcome_screen" src="https://user-images.githubusercontent.com/49511/33333212-91e18274-d423-11e7-92b8-19923012bb32.png">

Here's the Invision for reference: https://mozilla.invisionapp.com/share/MHEBCD4PK#/screens/264173555

Worth highlighting (@m_and_m) is the desire to have a "Sign In" to get set re-started. I feel this may not be feasible nor apply until we have sync in place?

**Comment by devinreams** [comment]
@sandysage We've been (hopefully correctly) assuming the UI/UX implemented at #362 (FxA) and #331 (Photon styles) satisfies this "first-run" story.

Is that still accurate or should we split out anything else as a "todo"?

**Comment by sandysage** [comment]
@devinreams I think the only thing I'm not seeing are the first-run instructions:
![screenshot-2017-12-6 lockbox fx add-on preview mode - invision](https://user-images.githubusercontent.com/850418/33677524-4cbd9b48-da76-11e7-84c7-a9f164c824e8.png)

Should that be captured in the Photon updates of #331 or opened as it's own issue?

**Comment by devinreams** [comment]
>I think the only thing I'm not seeing are the first-run instructions:

Ah yes, we call that the empty state or 0-entries welcome page and have it called out in #331 as a "to do" still.

So, it sounds like we're indeed covered here with the work planned. 👍

**Comment by changecourse** [comment]
Here are updated images @devinreams and @jimporter to remove + and the copy feedback...

![promo 1](https://user-images.githubusercontent.com/6164801/33786378-280b8f10-dc26-11e7-9dd4-3d48cebe8d9e.png)
![promo 2](https://user-images.githubusercontent.com/6164801/33786379-28211e98-dc26-11e7-9615-85d7dd7d1078.png)
![promo 3](https://user-images.githubusercontent.com/6164801/33786380-2836185c-dc26-11e7-8001-81824c7b15a3.png)

**Comment by changecourse** [comment]
I figured we'd programmatically apply the border and shadow to these, as seen in Zeplin.
