### ISSUE TITLE
Update Lockie

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#296]
I think it's time to do another pass to update Lockie. In particular, I'm thinking about the following things:

1. Remove the ASCII art
2. Remove Lockie's name from the UI (it's a goofy pun and I've always considered it more of an Easter Egg than an "official" thing)

@changecourse Thoughts?

**Comment by changecourse** [comment]
Agreed for both #1 and #2, and I think handling #191 alongside this will replace the ASCII with the svg in the home state of the Lockie illustration.
