### ISSUE TITLE
Update styles so favicon inverts colors when expected

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#308]
Looked into this at #306 with context-fill but didn't get far enough.

Now you see it...

<img width="455" alt="screen shot 2017-11-10 at 6 30 41 am" src="https://user-images.githubusercontent.com/49511/32660603-ca27a5a6-c5e0-11e7-88c6-3cff4c69b4f9.png">

Now you don't...

<img width="450" alt="screen shot 2017-11-10 at 6 30 51 am" src="https://user-images.githubusercontent.com/49511/32660618-d49c5158-c5e0-11e7-8987-52f4d34eef8b.png">

Opening an issue to come back to later (or in case anyone readily knows the answer).

**Comment by devinreams** [comment]
Aha, `chrome://` tabs get the "currentColor" fill which makes this possible:
https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/tabs.inc.css#214-217

If `moz-extension://` could too then we'd be in good shape and get a better favicon "for free". Tested a quick 1-line CSS change on my local Nightly and worked as expected:

![currentcolor](https://user-images.githubusercontent.com/49511/32673718-6d599c3a-c60d-11e7-9731-18c742023b13.gif)

@jimporter What do you think? Could we explore theme-ing/changing the tab styles ourselves to get this result? My bugzilla search skills are a bit weak still but do you also think a) this is worth opening up a bug about, if not already and b) submitting a patch to consider?

**Comment by jimporter** [comment]
We should probably just file a bug on Bugzilla.

**Comment by devinreams** [comment]
This magically works for free now 🤘 

![favicon](https://user-images.githubusercontent.com/49511/37935629-7fb84814-310f-11e8-960f-ebdb5331e567.gif)

See how our lock icon switches from dark to light when on a light and dark background, respectively (unlike GitHub). Neat! 🎉
