### ISSUE TITLE
firstrun page is missing favicon

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#309]
Spotted in #303 output from the firstrun/index.html page:

```html
<link href="" rel="shortcut icon" type="image/svg">
```

I _think_ we just need to specify an `icon` property in the webpack file:

```js
    new HTMLWebpackPlugin({
      template: "template.ejs",
      filename: "webextension/firstrun/index.html",
      chunks: ["webextension/firstrun/index"],
      inject: false,
      minify: htmlMinifyOptions,
      icon: "../icons/lb_locked.svg",
    }),
```

### Before:

<img width="256" alt="menubar_and_welcome_to_lockbox" src="https://user-images.githubusercontent.com/557895/32666131-591a57ae-c5eb-11e7-990f-709f7045b627.png">

### After:

<img width="292" alt="with_lock" src="https://user-images.githubusercontent.com/557895/32666159-69bc9040-c5eb-11e7-9810-a0cc6be5cb0e.png">

**Comment by devinreams** [comment]
Thanks! I noticed this but completely forgot to get it fixed up. I blame my terrible context switching...

Good looking out!
