### ISSUE TITLE
Quick access to entry details if only one entry exists/matches for that URI

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#316]

**Comment by changecourse** [comment]
I don't think we'd want this behavior, as it could be jarring to be dropped into the details automatically, especially in use cases where someone is looking for credentials/entries independent of the context that they are in (their current, active tab)

It may be nice to default the focus state border to the item (if there is only 1 matching entry) though @jimporter had mentioned a potential bug around focus states for the list view on the doorhanger that I believe was tied more to Firefox itself...

**Comment by sandysage** [comment]
Agreed. I think this aligns with what @devinreams posted in #317 

> If just one matching result, open directly into it (show the detailed facebook.com entry).
> Another UX option would be to have it live alongside (quick access to the entry).
> May want to be an option, some users may expect to open this and not need the current page (on facebook.com but want to grab my pinterest password). Approach first is design for one contextual experience.

**Comment by changecourse** [comment]
Are we covered by #443 and #317 such that we can close this issue, @sandysage ?

**Comment by sandysage** [comment]
@changecourse I think it depends on the design. I don't see that yet in #443. If there are alternative option(s) when there is only 1 relevant result, then we need to account for that. If not, then we can close this out.

**Comment by devinreams** [comment]
I believe this was satisfied 10 days after @sandysage's latest comment ☝️

From [this thread](https://github.com/mozilla-lockbox/lockbox-extension/issues/443#issuecomment-362001500):

>One Entry found for this site – display the entry card in a pre-populated search list, with available quick actions for copying username and password

And this is what was implemented at #616 and #624 (#520)
