### ISSUE TITLE
URI detection to populate search results in the doorhanger list

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#317]
When I have multiple entries for the same URI, I want to see all the relevant entries when clicking the Lockbox icon, so I don't have to sort through my many saved entries to find what I'm looking for.

## Acceptance criteria
- Should be able to retrieve credentials (username & password) in 6 clicks or less
   - Should be able to copy username without having to dig into entry details
   - Should be able to copy password without having to dig into entry details
- Should be able to access entry details quickly
- Should have quick access to ALL entries associated with the current root domain (not a special treatment as it's not the primary use case)
- Should be able to get back to full list of entries (not the primary use case but need to allow for it)
- Should behave like the current search filter to provide the relevant results

## Relevant User Stories
- [ ] #443 UI design for URI detection

**Comment by devinreams** [comment]
If on `facebook.com/*` multiple facebook.com matches show those results, filtered.

If just one matching result, open directly into it (show the detailed `facebook.com` entry).

Another UX option would be to have it live alongside (quick access to the entry).

May want to be an option, some users may expect to open this and not need the current page (on facebook.com but want to grab my pinterest password). Approach first is design for one contextual experience.

**Comment by changecourse** [comment]
I'd like to take some time to explore some potential options here... I think it may be interesting to handle URI detection in a slightly different way, or rather, more involved than just serving up entry details automatically, rather we could display a card/toast/whatever at the top of the expanded doorhanger with "quick actions" when the current tab matches an entry within Lockbox... 

Based on prioritization in the queue for sprint planning @sandysage I can put some ideas together soon for this.

**Comment by linuxwolf** [comment]
on finding a match, some (unrefined) thoughts on the algorithm: https://gist.github.com/linuxwolf/5722b60907826b47a97b10cf36676ca2

**Comment by jimporter** [comment]
Here's a public suffix list (run by Mozilla): https://publicsuffix.org/

We could copy this into our build or maybe build a WebExtension API that lets anyone grab the "root domain" of a site. I imagine a lot of other addons would find it useful.

**Comment by sandysage** [comment]
With the creation of the follow up items in #498, this is now a duplicate of #341
