### ISSUE TITLE
Copy action verification to inform a user when a username/password is copied to the clipboard

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#318]
When I copy my username or password, to populate a web form, I want verification that the item is copied to my clipboard, so that I can confirm that I'm pasting the right information into the field.

<img width="1020" alt="screen shot 2017-11-08 at 3 38 12 pm" src="https://user-images.githubusercontent.com/850418/32673155-38da67e8-c60b-11e7-8355-745f7f57dc80.png">

## Acceptance Criteria
- Should have indication when either a username or a password is copied

## Expected behavior
- When "copy" action is clicked, next to either the username or the password, the "copied" feedback text appears
- "Copied" only shows next to either username or password, not both at once, to indicate which of the fields is copied to the clipboard
- The "copied" text is static and replaces the button when the item is copied to the clipboard
- Copied feedback shows for 3 seconds on a timer, then reverts back to the copy link
- Copied feedback is provided in both the mini-editor and the full-screen editor

**Comment by devinreams** [comment]
@sandysage @changecourse This is not intended to be exclusive to the "mini" doorhanger but the "full" management experience too, right?

**Comment by changecourse** [comment]
Correct, it would be nice to have this feedback universal to both experiences.

**Comment by jimporter** [comment]
@changecourse How does a user copy the same value a second time? Does the "Copied" text ever reset back to "Copy"?

**Comment by changecourse** [comment]
It does, my thought was that the copied feedback shows for 3 seconds on a timer, then reverts back to the copy link.

**Comment by jimporter** [comment]
Ok, cool. I'll keep that in mind when I implement this. Should the "Copied" text still count as a button/link just in case a user needs to click it again within those 3 seconds?

**Comment by changecourse** [comment]
Oh, interesting... My initial thought would be no, it replaces the button with static text, which I think we'd be ok with in most use cases.
