### ISSUE TITLE
Tweak doorhanger to say "master password"

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#321]
Per https://github.com/mozilla-lockbox/lockbox-extension/pull/295#issuecomment-343554611,

> Possibly unrelated to everything, but I notice in the [screenshot above](https://github.com/mozilla-lockbox/lockbox-extension/pull/295#issuecomment-343299179) it says "Enter your password" in the doorhanger. Shouldn't that say "Enter your master password" to be consistent with the firstrun experience?
> 
> ![](https://user-images.githubusercontent.com/557895/32673499-560926e4-c604-11e7-818d-15e1efb919b2.png)
> 
> vs:
> 
> ![](https://user-images.githubusercontent.com/49511/32630555-3f27bcd8-c55a-11e7-9f21-bf45fca67ec5.png)

Easy fix, I'll PR shortly.

**Comment by devinreams** [comment]
>Easy fix, I'll PR shortly.

You stumbled onto something here, @pdehaan. I believe there is a pending content/copy decision on what to actually call it (hint: maybe not master password as it may not remain for much longer). @sandysage can shed light on that..

**Comment by pdehaan** [comment]
PR #322

**Comment by sandysage** [comment]
@pdehaan This is a good catch. But any effort put forth here wouldn't be retained in near(ish) updates. We go into great detail in #209 around the changes to how users secure (lock) their Lockbox. One implication of this change is the account email and password becomes the digital key (master password). So the current implementation of "master password" goes away.

**Comment by m8ttyB** [comment]
What's the time frame for the FxA flows landing?

**Comment by devinreams** [comment]
>What's the time frame for the FxA flows landing?

ASAP. You'll note [the tracking issue](https://github.com/mozilla-lockbox/lockbox-extension/issues/209) @sandysage referenced above was ambitiously moved into the next milestone (0.1.3) as it's a must-have for Beta. 😁

**Comment by m8ttyB** [comment]
Let's bump this to `WONTFIX` .. @pdehaan keep those uber nits coming. They are appreciated.
