### ISSUE TITLE
A few rogue references to Firefox 54 in the repo

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#326]
Per https://github.com/mozilla-lockbox/lockbox-extension/search?utf8=%E2%9C%93&q=54&type=

But I thought our min version was 57...

https://github.com/mozilla-lockbox/lockbox-extension/blob/f68fd65458599b46bdf1bb4897ccc9d2aa1dd7f5/.babelrc#L4

https://github.com/mozilla-lockbox/lockbox-extension/blob/3d5c28488fb96f348049abb16f13c6718d28f7ea/src/install.rdf.ejs#L21

https://github.com/mozilla-lockbox/lockbox-extension/blob/3d5c28488fb96f348049abb16f13c6718d28f7ea/package.json#L10

**Comment by jimporter** [comment]
As long as it works in 54+ (which it should, although we don't yet have tests to prove this), I don't think we should disallow users on older versions of Firefox from using this extension. It would be really nice if we could support <57 for users who don't want to move to a WebExtensions-only world just yet (provided there isn't anything we actually *need* from 57+).

We'll need **58+** for telemetry, but for earlier versions, we could just disable our telemetry recording and everything should work.

**Comment by m8ttyB** [comment]
A note from PI, currently the target audience that the team discussed is Firefox 57+ and is reflected in our test plan. Testing is occurring in 57+.

@pdehaan raises a fair question. Deferring this to Product for more guidance.

**Comment by sandysage** [comment]
To limit the amount of maintenance we need to support going out the door, and given our alignment to Photon, we need to explicitly only support 57+. Good catch @pdehann!
