### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#327]
Latest comps show 'settings'
![screenshot-2017-11-11 1 1 0 lockbox home - authenticated](https://user-images.githubusercontent.com/850418/32690291-b79c6058-c6b1-11e7-89c0-c2b748657c36.png)

I'm assuming the available settings include:
- [ ] sign out
- [ ] link to FxA settings

What am I missing here?

**Comment by linuxwolf** [comment]
We should also include a way for users to reset the local state.

**Comment by sandysage** [comment]
duplicate of #384
