### ISSUE TITLE
"Fira Sans Mono" for User Inputted Text

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#330]
Considering consistency of typography for user inputs based on the need for a monospace font in 3 of the 5 fields for an entry... 

<img width="455" alt="screen shot 2017-11-13 at 10 37 53 am" src="https://user-images.githubusercontent.com/63193/32740851-8a7bf6f4-c861-11e7-92c6-7d7c8d090fb1.png">

**Comment by devinreams** [comment]
Good catch, and sorry this wasn't called out explicitly sooner.

At #255 #295 @jimporter made a good call which is to also apply the momospace to username and address fields to help users for similar reasons as setting "password" to mono.

- users could get confused/phished by domain names (m0zilla vs mozilla)
- if you have to type a complex username, its the same problem as complex password (different 1 vs l vs L)

@changecourse this is _very_ easy to change in the code. I propose leaving as-is for now but happy to make adjustments you see fit...

**Comment by changecourse** [comment]
Agree that we'd want to do this to prevent phishing, but now wondering if we should make the design to just handle all inputted fields with the monospace font for the sake of visual consistency and understanding that all user-inputted content displays in the same way. 

Any objections @jimporter for us to just handle all fields with fira-monospace?

**Comment by jimporter** [comment]
@changecourse It might look a bit off for now, given that there are only 2 non-monospace fields. However, we've yet to add some of our other fields (e.g. tags), so there'll be a better balance in the future. I could also see making the origin variable-width, since the URL bar in Firefox is that way too. Username and password are the only ones that really need to be monospace.

**Comment by changecourse** [comment]
I understand that the only two fields absolutely required would be username and password... Origin could be argued either way... 

What I'm trying to rectify is the comprehension around inputs on the whole, and a perception that fonts entered into fields looking slightly different from one to the next will be mildly confusing at best, and concerning/distrustful at worst... 

Aside from Photon standards, would there be any negative consequences around us handling all user inputs with the monospace font?

**Comment by jimporter** [comment]
I think monospace tends to look strange for people (non-programmers) when it's for descriptive text. A sentence (such as would be in the notes section) would probably look "off". We're also looking at a sort of pathological case in the screenshot, where all the text in each field is the same, so the differences look more pronounced. In ordinary cases, I don't think it would look as weird.

**Comment by changecourse** [comment]
Ah, fair points. 

I'll go ahead an close this issue and we'll hold off on any changes unless there's a justifiable need in the future, via user testing or otherwise. Thanks @jimporter
