### ISSUE TITLE
Photon Updates, 2nd Pass

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#331]
~Depends on #338 (styles moving around a lot)~

Work at https://github.com/mozilla-lockbox/lockbox-extension/pull/351

Follow-up at #392 

Now that the design has firmed up a bit more, there are additional tasks to be completed for alignment to the prototype:

- [x] Navigation links (top right) to match the photon guidelines, found [here](http://design.firefox.com/photon/components/link.html) including external link icon
- [x] Vertical height of Nav bar, 72px
- [x] Moving entries counter into primary content area (You have __ entries in your Lockbox)
- [x] Moving home next to "New Entry" and applying secondary button styling to it
- [x] Sidebar width (320px)
- [x] Styling of new entry in sidebar to match with content background of main content area, based on screenshot below: <img width="583" alt="screen shot 2017-11-13 at 11 43 35 am" src="https://user-images.githubusercontent.com/6164801/32742898-ff9c4cee-c867-11e7-9e80-7bbce505f46b.png">
- [x] Removal of horizontal divider in Create a New Entry & View Entry Details<img width="385" alt="screen shot 2017-11-13 at 11 44 51 am" src="https://user-images.githubusercontent.com/6164801/32742940-20ba234c-c868-11e7-9223-3c0e8793316a.png">
- [x] Change background color of primary content area when viewing or creating an entry to hex F3F3F5, as seen in latest design comps. 
- [x] Fix password and search input font color so its legible (very light, reported #264)
  <img width="681" alt="screen shot 2017-11-14 at 10 09 03 am" src="https://user-images.githubusercontent.com/49511/32793670-de8343b6-c923-11e7-9f55-b02f404e6f03.png">

---

Welcome and Homepage

- ~Disabled button states for both primary (blue) and secondary (grey)~ #361
- [x] 1.1.0 welcome screen width and fonts
- [ ] 1.1.0 zero entries / first run home page with 3-up feature heros
- ~Disabled "Home" button when not on a item detail (create, edit, view) view~ #361 

New Entry and Sidebar

- ~1.1.0 New Entry: Disable buttons for New Entry while creating a current entry (may be accounted for somewhere else)~ #361
- [x] revisit button sizes
- [x] "Site Address" and "Site Name" order and copy
- ~Disable "Save Entry" until at least one field has been populated (may be accounted for somewhere else)~ #361 
  ![screen shot 2017-11-30 at 4 00 25 pm](https://user-images.githubusercontent.com/49511/33459553-9b805a24-d5e7-11e7-9eaa-9acae14bbc06.png)

One Entry

- ~one entry view with Lockey and tagline and feature copy and FxA buttons~ #362 
- [ ] extend background of item details all the way to bottom of screen (content area is gray, white space beneath)

Sidebar

- [x] sidebar: border on all items except when item selected (and no arrow)
- [x] sidebar and doorhanger nav: Photon icon ["Arrowhead Right 16"](http://design.firefox.com/icons/viewer/)
- [ ] sidebar: secondary (no username)" and "(no site name)" CSS treatment (lighter color)
- [x] sidebar: zebra background colors conform to comps
- [ ] "Disabled"/inactivate/muted state of the sidebar list items when an item is selected (greys out all entries but the one selected)
- [ ] Search bar magnify icon ~and clear icon (when populated)~ based on screenshot below: <img width="260" alt="screen shot 2017-11-13 at 11 41 21 am" src="https://user-images.githubusercontent.com/6164801/32742816-b9918336-c867-11e7-995a-8de86e47d694.png">

Modal

- [ ] red alert button style for delete (keep primary for discard)
- [x] copy changes
- [x] modal rounded with subtle-er shadow

Doorhanger

- [ ] wider width for doorhanger?
- [ ] "manage lockbox" button shorter, background color? (instead of ghost button, make it a puffy?)
- [ ] entry details: move "title" to title bar (out of detail view)
- [ ] doorhanger search padding to have more space
- [x] entry details: background color 

Copy

- [ ] review all copy once again
- [x] borrow content from welcome or otherwise and drop into addon description

**Comment by devinreams** [comment]
@jimporter I'm thinking I'll take a pass at this while you work on other stuff, unless you tell me hands off. 

Given all the changes needed, may help inform what we need to do to refactor the CSS #319 (how much stuff is re-used, where, how, etc.).

**Comment by jimporter** [comment]
@devinreams Now might not be the best time to mess with styling, since I'm moving a lot of stuff around for the doorhanger PR. We'll probably end up with a bunch of merge conflicts.

**Comment by devinreams** [comment]
>I'm moving a lot of stuff around for the doorhanger PR. We'll probably end up with a bunch of merge conflicts.

Cool. I can wait and just branch off your branch then and get the benefit of what you've got, test against what's there.

Just looking for things I can help with... ⚒

**Comment by devinreams** [comment]
@changecourse do you think we should also add focus styles to buttons? added here: https://github.com/FirefoxUX/photon/commit/fdc40e1036030909ccb5098d261f7e48ef324ca6

**Comment by devinreams** [comment]
Holding due to additional Photon updates and input from @changecourse.

And an OK from @jimporter on how to work on this simultaneously (ideally, or after) #338

**Comment by devinreams** [comment]
I walked through the final mockups (in [Zeplin](https://app.zeplin.io/project/59fb4868c5e7608593f76965), matching [InVision](https://mozilla.invisionapp.com/share/MHEBCD4PK#/screens) with @changecourse today and updated the todo list above. ☝️ 

I may not get to everything myself at #351 but will mark off what I can do and then see about asking for help in separate branches/PRs.

I also spoke with @linuxwolf and it makes most sense for his FxA branch #362 to lead and this work to follow.

**Comment by devinreams** [comment]
I'm going to 🔨 call this branch good-enough and spin up a "3rd pass" issue to track the remaining open items so we can land this as-is: https://github.com/mozilla-lockbox/lockbox-extension/issues/392
