### ISSUE TITLE
Placeholder Text on Fields for Creating/Editing an Entry

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#332]
Where appropriate, I'd like to have input masks on entry fields, based on what is presented here: 
https://mozilla.invisionapp.com/share/CTEFRXMZ7#/263643956_1-1-0_Lockbox_Home_-_New_Entry_-_Unfilled 

I have them on every field, but if there's any concern about what is presented, we should discuss the approach in more detail during planning...

**Comment by jimporter** [comment]
@changecourse Are you talking about the placeholder values here? I'm not 100% clear on what an input mask is.

**Comment by changecourse** [comment]
Yes sir, the placeholder values for each field...

**Comment by henryhahn** [comment]
If you all are okay with it, I'll do this one!

**Comment by jimporter** [comment]
@henryhahn Go for it! You should only need to modify our `src/webextension/locales/en-US/manage.ftl` file to make this work. If you have any questions, just @ me.

**Comment by henryhahn** [comment]
@jimporter Thanks! I just posted a diff for this here: https://github.com/mozilla-lockbox/lockbox-extension/pull/336
