### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#345]
Placeholder for designs coming soon.

**Comment by devinreams** [comment]
@jimporter if I were to help build this would you be opposed to a new `faq.js/css` and a `go-faq.js` to add the content page itself and the button in the nav? 

I'd also probably need a pointer on getting the reducers and UI state right. But is that the right approach or would you rather a more abstract way to do nav vs content pages (home, FAQ, feedback)?

**Comment by pdehaan** [comment]
How do we feel about something like [TestPilot's /docs/faq.md](https://github.com/mozilla/testpilot/blob/master/docs/faq.md)? That way we don't need to worry about CSS or JavaScript, it's just Markdown.

**Comment by devinreams** [comment]
Sorry I was super vague and unclear.

New designs (that I realize I didn't link to yet) would actually put another content page in-app for users to browse to. 😁 

<img width="645" alt="screen shot 2017-11-16 at 5 56 13 pm" src="https://user-images.githubusercontent.com/49511/32923937-74343896-caf7-11e7-94a8-e727b67ea723.png">

**Comment by devinreams** [comment]
Open question to @changecourse @sandysage:

1. Dynamic website loaded in? meets user expectations? expected to pull in web content (require internet access), etc. put it on our existing website?

2. Packaging FAQ with addon? can't update until entire addon is updated.

---

Per discussion today: this may not be a long-term feature, will likely be re-considered, so first option feels best (send users to our website).

Guided tour would be a better solution to the overall "problem" vs "having static content", for example.

**Comment by devinreams** [comment]
@jimporter To close the loop here: this FAQ page is going to just be an externally hosted page to our github.io docs site (like our "Submit Feedback" link) so I'll open a PR to add another external link.

@sandysage Once you have final FAQ content let us know or feel free to drop it into the related docs PR here #386

**Comment by sandysage** [comment]
@devinreams Final FAQ content can be found [in this doc](https://docs.google.com/document/d/1X6nt9m8CV5Uix4VyIONala7Sm8TJUPGml7-u35vVYs8/edit?ts=5a272f54). This should now all be ready to go.
