### ISSUE TITLE
Update Telemetry events to conform to doorhanger metrics specs

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#358]
The new "doorhanger" was added at #338 (hidden/disabled except in dev modes) and new metrics specs added at #342.

Now that the two are in place, the Telemetry events need to be updated to distinguish those happening in the doorhanger.

- [ ] render event
- [ ] "Manage Lockbox" button (not in metrics.md spec)
- [ ] doorhangerItemSelected
- [ ] doorhangerItemCopied
- doorhangerAddClick (does not yet exist #354)

Does that look right @irrationalagent? You mentioned you wanted to take a stab 🔪 at this first so I set you as assignee.

**Comment by irrationalagent** [comment]
this looks good to me for now. I'll also add the manage button to the .md spec.

**Comment by devinreams** [comment]
From discussion today, @jimporter may need to refactor and help do this due to the common code. Set a context? Pass params? Redux middleware? Hmmm...

**Comment by devinreams** [comment]
From Slack: there's an In-progress middleware patch started by @jimporter at #385.

@jimporter says it'll be quick enough for him to wire up the doorhanger/full editor context himself. Removing @irrationalagent from assignee.
