### ISSUE TITLE
lockbox-extension API docs are empty

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#366]
Noticed that https://mozilla-lockbox.github.io/lockbox-extension/api/ seems empty.

<img width="1440" alt="api_guide_-_lockbox_extension_empty" src="https://user-images.githubusercontent.com/557895/33512202-ecdbd99a-d6df-11e7-8b49-e8c29ade6f71.png">

Not sure if this is related to https://github.com/mozilla-lockbox/lockbox-datastore/issues/59 or just pure coincidence.

**Comment by devinreams** [comment]
Ah the actual issue is no actual jsdoc (comments) exist in the code so no content exists. This is (unfortunately) as expected until @jimporter makes #51 happen. I'll remove from the TOC for now, though.

**Comment by devinreams** [comment]
Duplicate of #51
