### ISSUE TITLE
Enable doorhanger for production builds

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#377]
After quick discussion with @jimporter and after running it by @sandysage, the product team does want the doorhanger enabled for the next release (0.1.4) as the benefits outweigh the cost. For example, it enables easier copy/paste to happen faster, even if it doesn't allow editing/adding.

This relies on Telemetry https://github.com/mozilla-lockbox/lockbox-extension/issues/358 being in place first.

Anything to add or discuss @sandysage @jimporter?

**Comment by m8ttyB** [comment]
Just a note, PI has not done in-depth testing on the functionality that's been pref'd off in the door hanger. I'll re-scope the testing for this release. Please ping me when you get a chance so we can triage the acceptable risks for 0.1.4.

**Comment by sandysage** [comment]
Nothing to add. Agree with these points. And I just want to highlight the importance of this along with having the telemetry in place for the expected increase in use in the coming weeks.

**Comment by devinreams** [comment]
>PI has not done in-depth testing on the functionality that's been pref'd off in the door hanger. I'll re-scope the testing for this release. 

@m8ttyB Sorry I'm not following, the functionality has not changed from #338 (marked "pi-verified" and has unit tests).

We're just "un-preffing" so its actually exposed to users. Are you saying we need a manual test plan added? We can discuss later today.

**Comment by m8ttyB** [comment]
Circling back to close the loop, I caught up w/ @devinreams yesterday and explained that when we originally pref'd off this feature to allow for additional development, PI only did happy path testing in anticipation of more work being done in the future. The future is now :)

**Comment by devinreams** [comment]
@jimporter do you think we should rip out the "ENABLE_DOORHANGER" logic entirely? Or just default it to "1" for purposes of release/Alpha?
