### ISSUE TITLE
Add integration tests for FxA login, as well as doorhanger.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla-lockbox/lockbox-extension#378]
With the new door-hanger and fxa login flow landing, we will need to update the integration tests as well as expand their coverage. I am proposing a few new tests as well as a login flow update.

* [x] Update Login flow to accommodate FxA
  - [x] FxA Sign-in on welcome page.
  - [x] FxA Sign in on Home page from 'guest` mode.
  - [x] FxA Create account on Home page from 'guest' mode.
* [ ] Door-hanger
  - [ ] FxA Sign-in
  - [ ] Options button navigation
  - [x] Entry's matching
* [x] Guest Mode
  - [x] Add entry
  - [x] Delete entry

It would be nice to test the restart functionality, but I will get to that at the end if I have time as restarting Firefox isn't currently easy to do with selenium.

**Comment by devinreams** [comment]
>we will need to update the integration tests as well as expand their coverage. I am proposing a few new tests as well as a login flow update

Thanks! This list looks good and complete to me @jrbenny35.

I defer to @linuxwolf and @m8ttyB if they can think of anything else we should attempt to cover. The only thing I'd be curious to see if/how we should test is the actual FxA account creation step.

**Comment by linuxwolf** [comment]
> * [ ]  FxA Create account on welcome page.

The welcome page does not have a "Create account" button itself.  The "Get Started" button is what gets the user into Guest Mode.

**Comment by jrbenny35** [comment]
@linuxwolf is there a difference in adding an entry when a user is signed in vs guest mode?

**Comment by linuxwolf** [comment]
> is there a difference in adding an entry when a user is signed in vs guest mode?

@jrbenny35 there's no effective difference.  Once signed in (which, in guest mode, the user is always signed in), getting/adding/updating/deleting entries behaves the same.

**Comment by jrbenny35** [comment]
@linuxwolf I guess I mean any difference between FxA and guest mode with regards to adding/deleting entries.

**Comment by linuxwolf** [comment]
no difference @jrbenny35

**Comment by m8ttyB** [comment]
A check-point, these scenarios look great. The scenario that tests the guest mode flow is of higher priority for this release. That said, in talking to @jrbenny35 it sounds like the other testing flows are seeing good progress and are likely to land this week.

**Comment by jrbenny35** [comment]
Initial merge here: https://github.com/linuxwolf/lockbox-extension/pull/3
