### ISSUE TITLE
Nightly can no longer load our extension

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#38]
>The patch to flip the default setting to disallow legacy extensions is in autoland at the moment and, barring some snafu, should be in [Friday's] Nightly builds.

When I run `jpm`:

```
1502463800840	addons.xpi	WARN	disabling legacy extension lockbox@mozilla.org
1502463800841	addons.xpi	WARN	disabling legacy extension lockbox@mozilla.org
1502463800841	addons.xpi	WARN	disabling legacy extension lockbox@mozilla.org
```

When I try to load `dist/install.rdf` manually at `about:debugging`:

![screen shot 2017-08-11 at 9 05 23 am](https://user-images.githubusercontent.com/49511/29219143-66434a1c-7e74-11e7-9947-74999eb416af.png)

**Comment by devinreams** [comment]
Oh, if you flip `extensions.legacy.enabled` back then you can run on Nightly.

Also works fine on your own local builds with no extra hurdles.

Nothing to see here (for now)...

**Comment by linuxwolf** [comment]
This is worth a note in the README ...

**Comment by jimporter** [comment]
There is still an issue here: if you're using `npm run-script run`, it generates a new profile by default which doesn't have the pref set.

**Comment by devinreams** [comment]
>it generates a new profile by default which doesn't have the pref set

Ah yes, so is the only option to create/distribute a profile and have that pref set? I did a little research and can't tell if there's still a good way to have all profiles inherit "default" prefs, doesn't seem like it...

**Comment by jimporter** [comment]
I just locally patched `jpm` for my sanity. Maybe we could convince the add-ons team to release a small update that does what I did?

**Comment by devinreams** [comment]
>I just locally patched jpm for my sanity.

@jimporter Ah, ok.

It also looks like we can pass prefs directly to jpm. Care to check out #39 and see if it works for you?
