### ISSUE TITLE
Update docs to match latest copy content and messaging

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#382]
After reviewing the [proposed changes from the product team](https://docs.google.com/a/mozilla.com/presentation/d/1_ewyXzLglrmfUmK_RWiBR22dWzf29iFQ_VO0blMQgYQ/edit?usp=sharing_eil&ts=5a205c0c) I believe the todos are as follows:

- [x] update intro body copy
- [x] update navigation items and order
  - [x] include FAQs
- [x] add install and feedback callouts / popouts
- [x] add contribution callout / popout
- [ ] add tour (in lieu of carousel, heading + copy + screenshot, stacked top-down)

@sandysage can you help confirm:

1. an alternative approach to the tour that looks like this makes sense? (look good given technical constraints?)
  ![screen shot 2017-12-05 at 1 10 33 pm](https://user-images.githubusercontent.com/49511/33628357-b6f335cc-d9bd-11e7-8dba-132e8ed9c2ae.png)

2. the list above is complete/accurate based on what has been provided? (anything else?)

I've got a separate issue to tackle updating the main site with the callout here: https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/18

**Comment by sandysage** [comment]
> an alternative approach to the tour that looks like this makes sense? (look good given technical constraints?)

Yes. This is a good alternative approach. I included a note in the deck to all all the 'get started' text to appear before the instructions to ensure they don't get lost behind scrolling the steps.

> the list above is complete/accurate based on what has been provided? (anything else?)

This list is complete. But we do need to add a 'page' for FAQs. Do you want me to add that to https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/18 or create an issue for that new content page?

**Comment by devinreams** [comment]
>I included a note in the deck to all all the 'get started' text to appear before the instructions to ensure they don't get lost behind scrolling the steps.

OK! I'll have an update published to show/share shortly...
>This list is complete. But we do need to add a 'page' for FAQs.

Ah yes, I ignored that since I didn't see FAQs yet but did account for it in the nav updates.

**Comment by mheubusch** [comment]
@devinreams per the edits to the FAQs, I need to modify the copy on the Introduction page and the 4th tour step.  
Please change the second paragraph of the introduction to: Install it and sign in with your Firefox Account to encrypt your data with tamper-resistant block cipher technology. Then share feedback here. 


Change the 4th step to:  Sign up or sign in with a Firefox Account to encrypt and your entries.  (remove: and "back them up")


Also, because of the number of changes to the FAQ, can you replace them using the current document - it's probably too many changes to safely list each one out.

**Comment by devinreams** [comment]
>Please change the second paragraph of the introduction to...
>Change the 4th step to: Sign up or sign in with a Firefox Account to encrypt and your entries. (remove: and "back them up")

Done!

>because of the number of changes to the FAQ, can you replace them using the current document 

Yes, I've re-integrated the entire document. ✅ 

The latest is in place here https://github.com/mozilla-lockbox/lockbox-extension/pull/386 and ready to go live anytime, just say the word! 🏁
