### ISSUE TITLE
Fix integration tests so they don't need to sleep

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#401]
The browser seems to be moving slowly in some of the FxA tests as encountered on #351.

Perhaps we can use wait better than these sleeps?

**Comment by jrbenny35** [comment]
Should be fixed here: https://github.com/mozilla-lockbox/lockbox-extension/pull/351/commits/782428a33ba2874ae28eb602a371a4123a22eb83

**Comment by devinreams** [comment]
Thank you!
