### ISSUE TITLE
Upon uninstall, flip pref for "save logins" back if it was set

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#429]
Feature request to note if at installation the user _had_ the preference set for "save logins" set (and we then unset it) to set it back on upon un-installation.

**Comment by jimporter** [comment]
We already do this: https://github.com/mozilla-lockbox/lockbox-extension/blob/master/src/bootstrap.js#L210-L218

We also have automated tests for it: https://github.com/mozilla-lockbox/lockbox-extension/blob/master/test/unit/bootstrap-test.js#L132-L138

**Comment by devinreams** [comment]
Thank you. Sorry for the noise. I missed this when I was out and didn't know how to search for this good enuf apparently...
