### ISSUE TITLE
Converge on design decisions with the datastore repo

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#43]
We should make sure that we're doing roughly the same things in this extension and the datastore package. Here's a list of the stuff I can think of:

* [x] Babel configuration
* [x] Test frameworks (karma)
* [ ] Syntax (e.g. use of `import` vs `require`)

**Comment by jimporter** [comment]
For Babel, we can set things up so that the config depends on NODE_ENV: https://babeljs.io/docs/usage/babelrc/#env-option

**Comment by jimporter** [comment]
Babel configuration is being done in #46.

**Comment by devinreams** [comment]
>Test frameworks (karma)

@jimporter How much work do you expect it would take to get this running in karma so we know if stuff actually breaks? I ran into something earlier that caused the extension to "white screen" (do nothing) but tests passed. ✅

**Comment by jimporter** [comment]
I don't think karma is likely to solve that particular issue (at least not in general). We probably want integration tests where we actually run the packaged add-on and click on buttons. That's #52.

**Comment by devinreams** [comment]
> We probably want integration tests where we actually run the packaged add-on and click on buttons.

Cool. And forgive some of my ignorance here: I can just `rm -rf src/webextension/manage/locales`, run test ✅ and run build/run and everything compiles and looks fine, extension loads. But, obviously nothing pops into the screen.

Would that be easily confirm-able by running this in karma? If so that'd at be a nice first step on the path to full browser testing...

**Comment by jimporter** [comment]
It would be confirmable, but I'm not sure it's a bug; our l10n code is designed so that it doesn't show anything on the screen until our strings are translated. That way there's not a weird flash of untranslated text.

**Comment by jimporter** [comment]
I think we've converged enough here; the `import` vs `require` part has some legit reasons for why they're different (we're not a library, so we can use fancy-pants JS features without having to think about compatibility for users of our project). Closing this.
