### ISSUE TITLE
Clicking "New entry" button while editing an entry will duplicate the entry

### ISSUE THREAD

**Issue by cpeterso** [mozilla-lockbox/lockbox-extension#438]
Steps to reproduce:
1. Edit an existing entry.
2. While in the "Edit Entry Details" mode, click the "New entry" button.

Result:
A new entry will be created in "Create New Entry" mode, but the form will be populated with the previous entry's values from "Edit Entry Details" mode.

Is this a feature or a bug? This behavior was surprising because the shift from "Edit Entry Details" mode to "Create New Entry" mode was subtle and it wasn't clear at first that I was now editing a different entry with the same values.

**Comment by jimporter** [comment]
There are two possibilities here:

* Our Redux code is broken and we're not updating state properly
* Our React form is broken and doesn't reset its internal state when it should

**Comment by sandysage** [comment]
Let's investigate this further and determine next steps, which is what the estimate is for.

**Comment by m8ttyB** [comment]
@cpeterso good find! Thank you for filing the bug. I can repro this given your STR.

![lockbox_edit](https://user-images.githubusercontent.com/63193/34728569-71d5a23e-f517-11e7-9ad2-0c38e92fed33.gif)

**Comment by changecourse** [comment]
Yes, in the short term at least, I think we should disable the new entry button until you either save or discard changes. Thanks for catching this @cpeterso
