### ISSUE TITLE
Password generation test plan

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#441]
Goal
Password generation has been identified as a feature that will be available on Lockbox so that users can easily generate secure passwords.
The goal of our study is to evaluate designs for password generation on Lockbox in order to inform the first version of password generation in Lockbox Beta.
We’re interested in exploring how personalization of generated passwords impacts users’ experience.

Link to draft of research plan: https://docs.google.com/document/d/1UjCQ-QcIMzogZFSMUNfoYLsegU6xgw3-yK38xw28gqc/edit#

To do:
- Write test plan
- Create schedule
- Reach out to recruiter and provide with participant criteria
- Create schedule for participant sessions
- Share sign up sheet for note takers and observers

Acceptance criteria
Recommendations have been shared with team and broken into new cards for the backlog.

**Comment by hmcgaw** [comment]
Relevant links: 
HTML prototype: https://ericawright.github.io/lockbox-test/
Designs: https://mozilla.invisionapp.com/d/main#/console/12309826/273084820/preview
