### ISSUE TITLE
Planning to identify possible Lockbox hypotheses and methods for (in)validating them

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#445]
- [x] what events to track and why based on 2018 plans
- [x] survey ideas to inform possible hypotheses
- [ ] what hypotheses do we have for each of these events

**Comment by irrationalagent** [comment]
link to doc
https://docs.google.com/document/d/1pubqXKllo7l6fkJpik-QLZqPuBEFK1LZ2oUXTe6wlq0/edit

**Comment by sandysage** [comment]
We have a good draft around what we want to track and why. We're going to work through these more to evolve them into hypotheses we can test.

This also led to the survey ideas to run this quarter to better inform these hypotheses.

The plan is to close this issue when we address the remaining todo

**Comment by irrationalagent** [comment]
See https://github.com/mozilla-lockbox/lockbox-extension/blob/telemetry_leif/docs/metrics.md for a final-ish version of this

**Comment by sandysage** [comment]
And added to our hypotheses document in collaboration with Test Pilot: https://docs.google.com/document/d/1q2xYGsoB0ylfir-Bkg8BwP4Aj1H6OjjJHW2FmX-JexU/edit#heading=h.me7i9797y21i
