### ISSUE TITLE
Run pilot: Formative research on password generation using a prototype to better understand user attitudes and behaviors

### ISSUE THREAD

**Issue by hmcgaw** [mozilla-lockbox/lockbox-extension#452]
Goal
Password generation has been identified as a feature that will be available on Lockbox so that users can easily generate secure passwords. 
The goal of our study is to evaluate designs for password generation on Lockbox in order to inform the first version of password generation in Lockbox Beta. 
We’re interested in exploring how personalization of generated passwords impacts users’ experience. 

Link to draft of research plan: https://docs.google.com/document/d/1UjCQ-QcIMzogZFSMUNfoYLsegU6xgw3-yK38xw28gqc/edit#

Acceptance criteria
Recommendations have been shared with team and broken into new cards for the backlog.

**Comment by sandysage** [comment]
Dependent on #440
