### ISSUE TITLE
Create an Accessibility test plan

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#461]
Scope what is needed for an accessibility test plan. My proposal is https://docs.google.com/document/d/145Ce8SDqVmVWqe0RPGTnF-fxvZjwnop9EiM9L6WzVyw/edit.

Once scoped, I can break this into tasks that can be accomplished during our sprints.

**Comment by devinreams** [comment]
I believe this was performed here #497 and here #572 

Is live here:
https://mozilla-lockbox.github.io/lockbox-extension/developer/test-plan-accessibility/

(but worth noting, contains different content than what is in the Google Doc)

Triaging and closing as complete.
