### ISSUE TITLE
DR: Update the '0 entries' promo screen to align to photon

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#478]
*Adjustments to the first-time use, 0-entry screen*

**Inivsion: https://mozilla.invisionapp.com/share/W3EU997YN#/264245494_1-1-0_Lockbox_Home_-_0_Entries**

**Zeplin: https://zpl.io/an6g71l**

## Tasks ##
- [x] Change shadows on promo images to ‘Shadow 10’ instead of 30 in spec
- [x] Line-spacing for promo descriptions should be 22.5 (1.5x)

**Comment by jimporter** [comment]
@changecourse What's Shadow 10? I don't see it in the Photon spec...

**Comment by changecourse** [comment]
https://design.firefox.com/photon/patterns/shadows.html

**Comment by nickbrandt** [comment]
Holding off on this issue pending discussions.
