### ISSUE TITLE
Code coverage misses reducers.js

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#49]
Currently, our code coverage catches everything except reducers.js. This file is omitted because it's both 1) not tested yet, and 2) contains the object spread operator (which presumably confuses istanbul). There's no indication that the file is being excluded, which is concerning.

**Comment by jimporter** [comment]
This is "fixed" in that coverage checks this now, but the underlying issue is still present.

**Comment by devinreams** [comment]
Now that you have tests I don't think 1 applies (not tested) and can't tell if 2 is still an issue (object spread).

Looking at codecov it's green and happy:
https://codecov.io/gh/mozilla-lockbox/lockbox-extension/src/master/src/webextension/manage/reducers.js

@jimporter Is this safe to close?
