### ISSUE TITLE
PI - Scope accessibility test plan requirements

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#497]
Scope accessibility testing into individual stories that represent the various layers of inclusiveness.

The accessibility test plan will follow these guidelines https://docs.google.com/document/d/145Ce8SDqVmVWqe0RPGTnF-fxvZjwnop9EiM9L6WzVyw/edit?usp=sharing

**Comment by m8ttyB** [comment]
@kimberlythegeek check-pointed with me today, the scoping has begun, once drafted she'll attache a link to a Google Doc.

**Comment by kimberlythegeek** [comment]
Here's my current draft of the test plan. Also the [google doc is here](https://docs.google.com/document/d/1P71BtThg9rC9kXdGen9JRx46_QnTx033WLNZ4F1DEMU/edit?usp=sharing).


# Manual Test Plan

## KEYBOARD NAVIGATION

Navigate the web content using only the keyboard
- Tab Order: Verify that `TAB`, as well as `SHIFT + TAB`, follows a logical and intuitive order.
- Do all controls, such as links, buttons, etc., get focused? _(Focus should be visibly apparent)_
- If a modal or pop-up window opens does focus shifts to the pop up? 
  - Is focused constrained within the modal?
  - Can the modal be exited via keyboard? (`ESC` or cancel/exit button)
  - When a pop up window is closed, does focus return to a logical point? _(Such as where focus left off)_
- Does the webpage contain a "skip to content" link at the top of page? _(This may or may not be visible)_
- Ensure that all content that is visually hidden, and not meant to be available (especially in dynamic web applications) is also hidden from the keyboard and/or a screen reader.
  - Using `hidden` or `aria-hidden='true'` if necessary. _(See [hidden and aria-hidden](https://developer.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/))_

## PAGE STRUCTURE
- Do hyperlinks have text that give context? _(Can the purpose of the be understood in an isolated context? As opposed to a link reading "click here”)_
- Do all images contains an alt description? _Such a description should concisely explain the purpose of the image to a non-sighted user._
- Has a logical hierarchy of header tags been used?
- Does the page utilize [ARIA landmark roles](https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/aria-landmarks/)?
- Have ARIA attributes been put into use?
  - If using custom controls, have those controls been given the proper role attribute?
  - For custom controls, state changes must be provided via [ARIA states](http://www.w3.org/TR/wai-aria/states_and_properties#attrs_widgets_header).
- Form input fields and buttons must be labeled for screen reader users.

## COLOR
- Check for color contrast compliance:
  - Contrast ratio of 4.5:1 for normal text (less than 18 point or 14 point bold.)
  - Contrast ratio of 3:1 for large text (at least 18 point or 14 point bold).
- Information conveyed via color must also be available by other means. _(For example, a colored ink should also be underlined)_
- Buttons and links should be visually apparent when they have focus.
- Also consider how sites appear to users with varying types of colorblindness. _([See tools and resources](#tools-and-resources))_

## TOOLS AND RESOURCES
Use a variety of testing tools to analyze pages:
- aXe developer tools by Deque
  - [aXe browser extension](https://www.deque.com/products/axe/) 
- Browser developer tools to inspect HTML for logical heading structure and ARIA roles
- [Color blind simulators](https://www.toptal.com/designers/colorfilter)

**Comment by kimberlythegeek** [comment]
Still some fine-tuning to do, but as-is, this will probably cover 90-95% of accessibility issues.

**Comment by rbillings** [comment]
I'm curious, is there agreement to follow all of the accessibility rules? If, for example, an ARIA attribute is missing does that automatically equal a bug?

nits:
If a modal or pop-up window opens does focus shifts to the pop up? 
>> shifts/shift

Do all images contains an alt description? 
>> contains/contain

Also consider how sites appear to users with varying types of colorblindness.
>> This would be better as an actionable sentence. ex: Site complies with X standard for color usage in regards to colorblindness.

**Comment by kimberlythegeek** [comment]
@rbillings Edits made. Thanks!

**Comment by kimberlythegeek** [comment]
Thanks @rbillings :)

**Comment by m8ttyB** [comment]
This looks good, for r=me, can you add estimates to how long each story will take to complete?

**Comment by kimberlythegeek** [comment]
@m8ttyB Made some edits. Added estimates, and removed a couple of rules that do not apply to Lockbox.

**Comment by m8ttyB** [comment]
r+ thanks @kimberlythegeek. This looks great.
