### ISSUE TITLE
Discovery around the scope of work to implement URI

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#498]
Determine implementation approach coming out of design. A collaboration with design (what has to change in the design for technical approach) and engineering (what approaches can we take).

Goals: an implementation approach for moving forward. Make sure #317 has all the details required to move forward into an engineering ticket.

**Comment by sandysage** [comment]
Deliverables: issues filed for the work to be done to accomplish #317. Will close this out when that work is scoped

**Comment by jimporter** [comment]
Here's how I plan to divide the work up:

1. Get the URL to the doorhanger and fill it into the search box
   1. At this point, we can just take the hostname (no protocol, no port) for simplicity.
   2. This will probably be handled by pulling the data (i.e. when the doorhanger opens, we'll use WebExtension APIs to grab the active tab's URL and then rip out the bit we care about).
2. Handle the zero-results case
   1. We'll have to add a distinction between user-entered filters and the autogenerated filter from (1).
   2. This will probably be something like a banner that shows up below the search box that says "no results", with the full list of entries below
3. Handle the one- (or two-) result case
   1. This depends on (2.i) to distinguish between when the user types in the filter and when we provide it.
   2. The particulars of how this will look are still being nailed down, but there'll be some way for people to more-quickly copy the username/password.
4. Implement a more-robust URL parser
   1. Based on https://gist.github.com/linuxwolf/5722b60907826b47a97b10cf36676ca2
   2. Use Mozilla public suffix list: https://publicsuffix.org/

**Comment by jimporter** [comment]
@linuxwolf @sandysage Does this look good? Anything else I should add?

**Comment by linuxwolf** [comment]
@jimporter Thanks! I think the breakdown makes sense.  Some comments:

* try to note what "gotchas" might be lurking in there (e.g., WebExtension permissions)
* It's worth swapping **item 2** and **item 3** in terms of prioritizing work
* I think **item 4** can be held off for another issue/task; by itself it's a decent amount of work to suss out, and we may very well want this to impact "add" and "edit" to have known-good data tostart.

In the case of 1- or 2-items filtered, do we want to distinguish between user-entered and the implicit?  @changecourse @sandysage

**Comment by sandysage** [comment]
In talking with @jimporter, it's not likely a significant effort to make that distinction. But if there isn't a strong argument for adding that refinement at this stage (not in market yet), I propose we consider that in the future if we see a) heavy use of both user enacted search along with our auto-search and b) confusion in providing those results. @changecourse does that work for you?

From here, I'm going to create user stories for each of these chunks of work to be handled somewhat independently of each other so we can have smallish sized pr's better breaking out the work.

**Comment by changecourse** [comment]
I agree @sandysage for now.
