### ISSUE TITLE
Heartbeat survey to better understand target audience behaviors on Firefox

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#499]
Based on the ideas generated here: https://docs.google.com/document/d/1wYlsiSFLIDdVUDIosmCseWhlpyhi2Jp4uzx20_aR7wI/edit

We're working with S&I to run a survey with Firefox participants around their password management use (and abandonment, trust with credentials and a computer, and access on mobile.

These are key components to success for Lockbox. For Lockbox adoption it would have to be true that:

1. there is a problem managing passwords which would require more than 1 or 2 unique passwords
2. would trust a computer to save passwords
3. need access to those passwords in other environments to warrant cross-device support

**Comment by m8ttyB** [comment]
Please add `needs-pi` if you would like our group to review this work.

**Comment by sandysage** [comment]
That is available here: https://www.surveygizmo.com/s3/4174133/Lockbox-Market-Research-Survey-1
