### ISSUE TITLE
Newlines in Entry Details Notes are not displayed when viewing an entry.

### ISSUE THREAD

**Issue by cpeterso** [mozilla-lockbox/lockbox-extension#504]
I added some Notes to an Entry Detail using newlines to separate some key/value pairs. In "Edit Entry Details" mode, they look something like:
```
Fruit: Banana
Dessert: Ice Cream
```
But in the view mode, the newlines are not displayed, e.g.:
```
Fruit: Banana Dessert: Ice Cream
```

**Comment by m8ttyB** [comment]
Good find. I was able reproduce the behavior in both the `0.1.4` and `0.1.5` releases.  When returning to edit an entry with newlines, the edit mode correctly displays the text on the expected lines.

**Comment by jimporter** [comment]
I feel like we might have an issue on this already somewhere...

**Comment by devinreams** [comment]
>But in the view mode, the newlines are not displayed

Nice catch, thanks @cpeterso.

>I feel like we might have an issue on this already somewhere...

Yeah, I thought so too. This is slightly different than what we've seen before with _overflow_. I created a quick PR to add white-space wrapping over here: https://github.com/mozilla-lockbox/lockbox-extension/pull/596
