### ISSUE TITLE
Allow inserting password into specific password box

### ISSUE THREAD

**Issue by purajit** [mozilla-lockbox/lockbox-extension#512]
Currently, we have to copy the password and paste it into the password field, which is insecure since we're saving it to the clipboard. Moreover, some people use clipboard managers, which means that they have to remember to delete the entry, otherwise the password will stay saved for a considerable amount of time as plain text.

There should be an option that allows users to right click on a password box and select "Insert password" (or show an automatic dropdown/other alternatives)

(I agree that it shouldn't automatically insert it into the page for security reasons)

**Comment by jimporter** [comment]
This is covered in #495.

**Comment by linuxwolf** [comment]
duplicate #495
