### ISSUE TITLE
Create some integration tests

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#52]
We should have some tests that run against a fully-built XPI in the browser where we click buttons and make sure that stuff does what we expect. These probably don't need to be as thorough (yet?) as the unit tests, but some sanity checks would be good.

**Comment by m8ttyB** [comment]
@jrbenny35 is prototyping a test using Foxpuppet and Selenium that installs the extension from testpilot latest, creates an account/login, adds, and deletes entries. Current ETA is eod today, with a check-in if any additional blockers to his work are found.

Installation from testpilot latest is not the optimal solution. We will need to scope this.

/cc @jrbenny35, can you provide updates of your work here?

**Comment by jrbenny35** [comment]
I have 3 tests here on my branch: https://github.com/jrbenny35/lockbox-extension/tree/initial-integration-tests

I get around the signature issue by serving up the extension using a webserver and installing with the correct preferences set for firefox.

The tests use tox and they build the extension before installing it. Just clone the branch and type ```tox``` and they should run. You must have firefox in your path.

**Comment by jrbenny35** [comment]
Got some travis working: https://travis-ci.org/jrbenny35/lockbox-extension

**Comment by pdehaan** [comment]
Awesome work, @jrbenny35!

I was trying to play around with this a bit locally this afternoon and think we can maybe tweak up the selectors a bit in a few places in the source to make the selenium selectors a bit more stable. 

```js
export default function Welcome() {
  const welcomeCss = styles.welcome + ' boop';
  return (
    <section className={welcomeCss}>
      <Localized id="welcome-title">
        <h1>wELCOMe</h1>
      </Localized>
      <Localized id="welcome-intro">
        <p className="para1">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Sed
        posuere consectetur est at lobortis. Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur
        adipiscing elit. Etiam porta sem malesuada magna mollis euismod. Cras
        mattis consectetur purus sit amet fermentum.</p>
      </Localized>
```

Which produces something like the following source:

```html
<section class="welcome__welcome___151cF boop">
  <h1>Welcome to Lockbox (Alpha)</h1>
  <p class="para1">You've just installed the Lockbox browser extension! This Alpha prototype will give you the ability to create new entries, and then later you can view, search, edit, and delete those entries.</p>
  <p><strong class="para2">This is a rapidly evolving prototype that will change as Alpha progresses. Any data stored here is not guaranteed to be retained in future updates.</strong></p>
  <p>Please be sure to let us know your thoughts using our feedback button within the tool, including any issues you may find, things you like, and the things you're looking forward to in the future.</p>
</section>
```

So now instead of having to hard code dynamically created CSS selector names (welcome__welcome___151cF), we can just use the custom class names to make testing more reliable.

**Comment by m8ttyB** [comment]
@pdehaan On Friday @jrbenny35 is doing a show & tell for the Lockbox dev team. One of the items on the discussion list includes discussing test stability as it relates to CSS locators. We plan to work with the group to find consensus on a strategy that works for the team.

**Comment by jimporter** [comment]
Can't we select the element we want via the DOM's structure? I've done my best to use semantic elements to make it easier to figure out what's what (e.g. the item list in the management page is in an `<aside>` and the main content is in an `<article>`). I'm not too keen on providing dummy class names for tests since the whole point of how we munge class names was to keep our CSS as scoped as possible.

In any case, these tests are going in this repo, right? If they break because we changed the DOM structure, then it's the job of whoever broke it (probably me, at least for the time being) to fix the integration tests.

**Comment by jimporter** [comment]
We could also just replicate the CSS class name munger. It's just filename + class name + a base64-encoded MD5 sum of the path and classname separated by "+". I could probably get that working in a few minutes provided I figure out how the base64 encoding works (or we could just use hex instead, which I already have working).

**Comment by jimporter** [comment]
And here's working code to get the munged class names:

```python
import hashlib

table = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_'

def munged_class_name(path, name, length=5):
    h = hashlib.md5(path + '+' + name).digest()
    i = reduce(lambda x, y: x * 256 + ord(y), reversed(h), 0)
    s = ''
    while i > 0:
        s = table[i % 64] + s
        i /= 64
    return s[:length]
```

**Comment by jrbenny35** [comment]
Also, do class names changed based on releases?

**Comment by jimporter** [comment]
> Can you explain this a bit more?

Our CSS uses munged names as a way of scoping our CSS to specific files/modules. If we start using non-munged names, those names are essentially global scope, so *any* CSS file (including, potentially, ones injected by the browser) might have those class names. It's not terribly likely to happen at the moment, since we could just exercise good discipline and not use our unmunged CSS classnames for styling, but I'd prefer to make it hard for people to do that by simply not having those classnames around in the first place.

> Also, do class names changed based on releases?

I mentioned it above, but class names are munged based on the path to the CSS file and the "local" class name. So if I have a class in `webextension/widgets/button.css` named `button`, then the class name will always* be `button__button___267m4`. Per the Python code above, that's `<filename-without-extension>__<class-name>___<hash(full-path, class-name)>`. `hash` takes the full path and the class name, joins them with a `+` between them, then takes the MD5 sum of that string, turns it into base64 (using a somewhat-strange implementation) and truncates that to 5 characters.

\* Unless we change the munging function, which I don't see any reason to.

**Comment by jrbenny35** [comment]
@jimporter So you can style the button in ```webextension/widgets/button.css``` with the munged name? I've never heard of this concept so excuse my newbness.

**Comment by jimporter** [comment]
@jrbenny35 So basically what's happening is Webpack reads all our CSS files and generates new, munged names for all the class names in those CSS files. Then it spits out those munged CSS files for us to use*. It *also* gives us a little JS object in our JS files that maps unmunged names to the munged ones. So in our JS, we just use the regular, unmunged names, but Webpack is helping us translate them to the munged version. The Python snippet I posted above is basically replicating what Webpack does for us.

However, one thing I forgot to mention above is that, at least until now, I've considered all our class names to be implementation details that can change at any time. DOM structure is a bit more stable and I'm only likely to change it when we're making significant changes to the UI anyway. If it's possible, I think the tests would be more stable if they relied on the DOM structure (and other HTML attributes) than the class names specifically. Still, in a pinch, we can derive the munged class names pretty easily, so if you really need them for something, you can definitely use them.

* How it does this depends on whether it's a production or a dev build, but it's not really important.

**Comment by jrbenny35** [comment]
Could we do something like option 3 in the first answer? https://github.com/css-modules/css-modules/issues/194#issue-191368006

**Comment by jimporter** [comment]
I mean, we *could*. But that's just munging the class names in a slightly-simpler fashion, so the only benefit is that the names are easier to type manually. It's about equivalent to using the `munged_class_name` function I wrote above.

However, doing this would add more (unnecessary) differences between dev builds and production builds. Without that change, it should be possible to run these integration tests against production builds *and* dev builds, which would be a nice way of assuring us that we didn't screw up our production configs somehow.

**Comment by devinreams** [comment]
Thanks again for the walkthrough today @jrbenny35

We look forward to seeing your PR with the tests and docs we talked about. If you hit any snags getting the Python (for class selectors @jimporter dropped above) no worries, we can probably take a look at that together.

**Comment by pdehaan** [comment]
@jimporter Can you help me get the `munged_class_name()` method to work with the following selector from @jrbenny35's e2e test PR?

```py
_save_entry_locator = (By.CSS_SELECTOR, 'article div form menu '
                       'button.button__button___267m4')
```

I've tried a bunch of different variations, but cannot seem to get the generated hash to match the hard coded value.

**Comment by jimporter** [comment]
I think I saw someone mention that this was using Python 3, so here's a Python 3 version of my code, with an example of its use: https://ideone.com/b4wD00
