### ISSUE TITLE
Add telemetry scalars to better understand the datastore sizes

### ISSUE THREAD

**Issue by irrationalagent** [mozilla-lockbox/lockbox-extension#526]
We can now add scalars to our telemetry. We should do this so we can count people's datastore size directly without having to infer from event telemetry. see https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/scalars.html

**Comment by irrationalagent** [comment]
#552

**Comment by devinreams** [comment]
I believe this was _fully_ closed by #552 as that addressed the data store size scalar and does not need to remain open as all work is complete.

**Comment by linuxwolf** [comment]
That is correct; thought everything was set correctly for automatically closing this, but thanks for confirming (-:
