### ISSUE TITLE
Extension item details: click to reveal and copy (login, password)

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#53]
A quick search turned up some straight forward npm packages for both but not sure if they're worth incorporating as a dependency vs. rolling our own.

- click to reveal (input type password vs text)
  - https://www.npmjs.com/package/react-password-mask

- click to copy (grab input contents to clipboard)
  - https://www.npmjs.com/package/react-copy-to-clipboard

Any strong opinions one way or another (build ourselves vs package) @jimporter @linuxwolf?

**Comment by jimporter** [comment]
Both seem simple enough that it's probably less effort for us to roll our own; that way, it'll be easier for us to make tweaks as needed.

**Comment by devinreams** [comment]
@jimporter Agreed. Wanna run at it after lock/unlock?

**Comment by linuxwolf** [comment]
This should include the ability to copy the username, too.
