### ISSUE TITLE
Onboarding confirmation with security theatre (onboarding)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#535]
When I’ve successfully authenticated with FxA, I want to know that my logins have been added to my Lockbox and that I am ready to use the app

## Acceptance criteria 
* Should showcase the security of the product
* Should include an option to learn more about the security which deep links to an FAQ
* Should confirm that a user is finished with the first-run setup and ready to launch their Lockbox.
* Should be the final step as part of the first-run onboarding experience.

**Comment by changecourse** [comment]
@sandysage even though I initially pulled this in for this sprint, I think we should hold off on doing this work until we can tell a better story (from a brand positioning perspective)

**Comment by sandysage** [comment]
We've consistently heard throughout user research that there are concerns about the 'safety' of a solution especially when that solution has access to lots of passwords (not just one account). This is an opportunity to convey strong security along with the access product benefits.

**Comment by sandysage** [comment]
opened in the wrong repo...
