### ISSUE TITLE
PI - Color contrast is sufficient, and remains sufficient when simulating colorblindness.

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla-lockbox/lockbox-extension#540]
_< 1 hour_
- Text has sufficient color contrast against its background.
  - Contrast ratio of 4.5:1 for normal text (less than 18 point or 14 point bold.)
  - Contrast ratio of 3:1 for large text (at least 18 point or 14 point bold).
- Information conveyed via color is also available by other means.
- Buttons and links are visually apparent when they have focus.
- Focus remains apparent, and contrast remains sufficient, when simulating varying types of colorblindness.
  - [Color blind simulator](https://www.toptal.com/designers/colorfilter)

**Comment by kimberlythegeek** [comment]
Have not received mockups to test for color contrast, but have run automated tests, which include color contrast checks.

**Comment by m8ttyB** [comment]
Just doing some paper shuffling - PI has access to the mocks via zeplin, thank you Ryan.
