### ISSUE TITLE
Accessibility Considerations for UX Designs

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla-lockbox/lockbox-extension#541]
## UX Design Considerations
- Mouse interaction is not assumed.
  - Interactions available with a mouse are also available using a keyboard.
- Information conveyed visually is also available by other means.
  - Pop-ups and other state changes are announced to screen readers using appropriate ARIA attributes.
  - Temporary on-screen events give users ample time to receive conveyed information.
- Animations are not excessively flashy, as this can cause seizures in some users.

**Comment by m8ttyB** [comment]
Note, this is a chore for PI. A components of this task include:
* briefly discuss (if needed) the suggestions with @changecourse. 
* update the test plan to include these considerations
* Yura will share an example of a UX design that includes artifacts for these considerations. We can decide if they are helpful and warrant integration into our PI workflows.

**Comment by m8ttyB** [comment]
@kimberlythegeek can you give a update on what remains to complete this ticket?

**Comment by kimberlythegeek** [comment]
The only active **to-do** in this area is checking color contrast, which I will do as needed with mockups from @changecourse in Zeplin.

Everything else is more something to keep in mind, and will be reviewed for accessibility _after_ features have been developed.

**Comment by m8ttyB** [comment]
Re-opening, there are few items on the acceptance criteria (the checklist) that we need to follow up on. I've schedule a a meeting with @kimberlythegeek and @changecourse to know this one out.

**Comment by m8ttyB** [comment]
Closing this out, I think we missed marking this as complete after our meeting with product.
