### ISSUE TITLE
Create a shared component for Search

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#561]
The visual look and feel, as well as the functionality of the search bar is the same for both the full-editor view and the doorhanger view, thus we should use a shared component that is defined and styled in one place for both instances. 

<img width="610" alt="screen shot 2018-02-21 at 2 41 59 pm" src="https://user-images.githubusercontent.com/6164801/36506964-7149a336-1715-11e8-845d-207e39ab8483.png">

<img width="373" alt="screen shot 2018-02-21 at 2 42 13 pm" src="https://user-images.githubusercontent.com/6164801/36506965-715d82fc-1715-11e8-96a4-e3c8c70ae1d3.png">

Nick is currently working on a PR to ensure that the full-page editor search component matches our design spec. This component should be used as our baseline, which the doorhanger could inherit.

**Comment by linuxwolf** [comment]
As the list view in doorhanger and full editor converge on visuals and basic interactions, we might want to expand the scope of the shared widget to encompass the just about the whole list.

**Comment by devinreams** [comment]
I think this is indeed complete as the `<ItemFilter>` code is re-used in both places from what I see. Please speak now if this was accidentally closed with #562.

https://github.com/mozilla-lockbox/lockbox-extension/blob/master/src/webextension/list/manage/components/app.js#L43-L46

https://github.com/mozilla-lockbox/lockbox-extension/blob/master/src/webextension/list/popup/components/item-list-panel.js#L26
