### ISSUE TITLE
[regression] After logging in with FxA, quiting the browser prevents Lockbox from opening

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#568]
On a fresh Firefox profile, install [Lockbox latest 0.1.7-alpha](http://testpilot.firefox.com/files/lockbox@mozilla.com/latest) from Test Pilot, sign in with an existing FxA account (or create a new one). Quitting the browser without signing out appears to break Lockbox. The toolbar icon becomes unresponsive.

Reproduced on Nightly and Beta. Curiously, I cannot reproduce this with a profile that had 0.1.6 installed previously.

![lockbox_0 1 7-alpha-fxa-bug](https://user-images.githubusercontent.com/63193/36609285-95d32cde-1889-11e8-8052-90b474ca3f12.gif)

## STR
0. Install Lockbox latest on a clean profile for nightly
1. Sign into Lockbox with an existing FxA
2. Quit Firefox (vs. signing out of Lockbox)
3. Open Firefox with same profile and click the toolbar icon

## Expected
The toolbar icon prompts the user to sign in

# Actual
The toolbar icon is non-responsive

**Comment by linuxwolf** [comment]
From my reproducing this, it appears to be caused by the FxA account info never making it to local storage. Existing upgrades that were already linked would work, but new installs and existing upgrades that *are not linked* would have this problem.
