### ISSUE TITLE
Reset Lockbox button displays as cut off

### ISSUE THREAD

**Issue by rbillings** [mozilla-lockbox/lockbox-extension#569]
When looking at Lockbox Preferences, the 'Reset Lockbox' button displays as cut off even when browser window is maximized. There is a hidden scrollbar that allows the user to see the full button, but it shouldn't be needed when browser window is at maximum width/height.

<img width="891" alt="reset" src="https://user-images.githubusercontent.com/737878/36609633-5f4f456e-1882-11e8-9df7-91b69a2db2bb.png">

**Comment by devinreams** [comment]
UGH! This has been bugging 🐛 me too, @rbillings. Thanks for filing the issue.

I just submitted a change to fix this here: https://github.com/mozilla-lockbox/lockbox-extension/pull/603
