### ISSUE TITLE
"Search Lockbox Entries" field should auto-focus

### ISSUE THREAD

**Issue by cpeterso** [mozilla-lockbox/lockbox-extension#573]
The "Search Lockbox Entries" fields in the Lockbox door hanger and "Manage Lockbox" page should auto-focus when they open. It is a frustrating break in my workflow to have to manually mouse over and click to focus the "Search Lockbox Entries" field instead of just immediately typing after opening the door hanger or "Manage Lockbox" page.

**Comment by devinreams** [comment]
@cpeterso I agree and started a quick change here. It may be a little _too_ simplistic but may be an acceptable start: #595

**Comment by devinreams** [comment]
My quick-n-dirty hack was _not_ a good approach and we'll have to keep this in the backlog to prioritize later. @jimporter provided comments at https://github.com/mozilla-lockbox/lockbox-extension/pull/595#pullrequestreview-100174330 worth reviewing when we come back to addressing this.
