### ISSUE TITLE
No new profile created using 'npm run run'

### ISSUE THREAD

**Issue by rbillings** [mozilla-lockbox/lockbox-extension#579]
I noticed that my profile manager no longer appears after sending the 'npm run run' command.  This is set as the default on my machine, and it does appear when manually opening versions of Firefox. 

The terminal does say "JPM [info] Creating a new profile", however it is opening the browser with the last profile I created. I verified this by running 'npm run run', and then going to about:profiles & it confirmed that I was using a profile I previously created.

**Comment by linuxwolf** [comment]
Without any additional settings, `jpm` copies your default profile to a temporary directory and uses that copy.  However, `about:profiles` does not indicate that is the profile in use; instead it points to what your default profile would normally be.

Our [install page](https://github.com/mozilla-lockbox/lockbox-extension/blob/master/docs/install.md) provides some guidance for profile use.

**Comment by rbillings** [comment]
I did not set any additional config values - and while I question it now, I swear the profile manager appeared before opening Nightly in the past, just like I have it set to do.

About:profiles shows me "This is the profile in use and it cannot be deleted." - is that not actually the one in use? That's strange.

**Comment by rbillings** [comment]
I did some more research and found that a temporary FF profile is created, although I still can't find the files on my local drive. The about:profiles page also seems to show the default and not the current profile- although generally they are one and the same. Resolving this as (strange but) Not a Bug!

**Comment by m8ttyB** [comment]
The more you know ..
