### ISSUE TITLE
Code Review Issues from #570

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#582]
Here are the issues I found from a post-review of #570; cc @linuxwolf 

https://github.com/mozilla-lockbox/lockbox-extension/blob/dbbce39ae648a3dde874b6d73503585f1a490e2c/src/webextension/background/accounts/index.js#L323-L325

Should we even bother creating a new account here? It seems like we should just error out. Perhaps this would break tests, but that just means our tests are broken. :)

https://github.com/mozilla-lockbox/lockbox-extension/blob/dbbce39ae648a3dde874b6d73503585f1a490e2c/src/webextension/background/browser-action.js#L68

Nit: Let's use `console.warn` since this is a warning-level log (though I'd lean towards making it an error as it sounds really bad).

https://github.com/mozilla-lockbox/lockbox-extension/blob/dbbce39ae648a3dde874b6d73503585f1a490e2c/src/webextension/background/index.js#L17

As above.

**Comment by linuxwolf** [comment]
> https://github.com/mozilla-lockbox/lockbox-extension/blob/dbbce39ae648a3dde874b6d73503585f1a490e2c/src/webextension/background/accounts/index.js#L323-L325
> 
> Should we even bother creating a new account here? It seems like we should just error out. Perhaps this would break tests, but that just means our tests are broken. :)

This is here because otherwise tests break; what's under test is not this result, or even the use of that result.  That and the time-sensitive nature of the fix is why it remained so far.

> https://github.com/mozilla-lockbox/lockbox-extension/blob/dbbce39ae648a3dde874b6d73503585f1a490e2c/src/webextension/background/browser-action.js#L68
> 
> Nit: Let's use `console.warn` since this is a warning-level log (though I'd lean towards making it an error as it sounds really bad).

Good catch; it was leftover from troubleshooting that the rest of us missed.
