### ISSUE TITLE
Create Account has 2 different forms

### ISSUE THREAD

**Issue by rbillings** [mozilla-lockbox/lockbox-extension#583]
The Create Account form sometimes has one password field, and sometimes it asks the user to repeat the password. I created 8 accounts in a row - 5 had 1 pw field, 3 had 2 pw fields. Both forms have similar urls:
https://accounts.firefox.com/oauth/signup?response_type=code&client_id=number&redirect_uri=https%3A%2F%2F2aa95473a5115d5f3deb36bb6875cf76f05e4c4d.extensions.allizom.org%2F&access_type=offline&scope=openid%20profile%20https%3A%2F%2Fidentity.mozilla.com%2Fapps%2Flockbox&state=number&code_challenge=number&code_challenge_method=S256&keys_jwk=number

I cannot isolate the specific repro steps that distinguish them. 
Steps:
1) create a new profile [I used the profile manager, and also about:profiles- no difference]
2) open lockbox with the new profile
3) click "getting started", click "create account"

expected: identical create account forms
actual: password fields vary, see screenshots

<img width="517" alt="screen shot 2018-02-27 at 10 44 34 am" src="https://user-images.githubusercontent.com/737878/36748993-595b0966-1bae-11e8-8aef-45409bb80539.png">
<img width="462" alt="screen shot 2018-02-27 at 10 50 54 am" src="https://user-images.githubusercontent.com/737878/36748997-5a9d5ea0-1bae-11e8-8d40-3ca9fbaebb6d.png">

**Comment by irrationalagent** [comment]
This is an a/b test that FxA has been running for awhile. The results are in, and they will be going with the two-field version everywhere. I believe the test is ending and rolling out to 100% soon. So expected behavior AFAIK

**Comment by jimporter** [comment]
Yeah, welcome to the magical mystery world of A/B testing. They're not *trying* to drive you mad; it's just a happy side effect. :)

**Comment by m8ttyB** [comment]
Good eye @rbillings! Transparency ftw

**Comment by rbillings** [comment]
I can take satisfaction in having the mystery solved!
