### ISSUE TITLE
Use a tests-specific eslint config

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#60]
The tests in #56 et al added boilerplate to permit the mocha globals.

A simpler solution is to have an eslint config specific to tests, (i.e., `./test/.eslintrc.js`) that configures these globals.  Also, that makes it easier to use the mocha plugin for eslint, thereby moving the symbol management to a common tool.

**Comment by jimporter** [comment]
I'm working on this and will probably just amend the relevant commit to make any potential code archaeology easier. (Unless you'd rather a new commit for it.)

**Comment by linuxwolf** [comment]
Whichever is best for you.  Added this issue based on the brief conversation in #56.

**Comment by jimporter** [comment]
Resolved in https://github.com/mozilla-lockbox/lockbox-extension/pull/56
