### ISSUE TITLE
Error States coverage and design

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#631]
placeholder card for 

1. audit of various error states required
2. designs to account for them
3. creation of future stories to address with ENG

https://docs.google.com/spreadsheets/d/1PNLL_-r1cgaNoKwyHOY534DuRqcR2xQdQCMa4pgKy0M/edit?ts=5aaaa8a6#gid=0

**Comment by devinreams** [comment]
@linuxwolf I attempted to start helping answer the questions in the inventory spreadsheet:

https://docs.google.com/spreadsheets/d/1PNLL_-r1cgaNoKwyHOY534DuRqcR2xQdQCMa4pgKy0M/edit?ts=5aaaa8a6#gid=0

But realized I had zero knowledge of the feasibility or things we could (or not) do to more gracefully handle these states. Can we ask for you to help "fill in the blanks"?

Then I think we all can collaborate asynchronously to assign some "Severity / Impact" number. For example, "device offline" is easy to solve (connect) and not super severe, but detecting and adding messaging for something that'll likely happen a lot would be a high impact and therefore higher prioritized state to solve for.

Is that cool?

**Comment by linuxwolf** [comment]
@changecourse I have already started to fill the blanks on that spreadsheet.  Will progress as time permits.

@devinreams as above, although I'm not sure a single number for both severity and impact will be sufficient to make an informed choice on prioritization.

**Comment by linuxwolf** [comment]
@changecourse @nickbrandt @devinreams 

Made a first-pass at the spreadsheet; I'm sure things could be better explained or accounted for, but will need some feedback for that.

**Comment by devinreams** [comment]
>Made a first-pass at the spreadsheet; I'm sure things could be better explained or accounted for, but will need some feedback for that.

@linuxwolf This is really helpful. I read through and think I've got a good handle on them all now. Thanks.

@changecourse @nickbrandt Depending on your priorities, please let me and Matt know if you want more context. We can do it however you prefer: a quick discussion, comments on the doc. Just let us know..

**Comment by changecourse** [comment]
@linuxwolf thanks for adding context throughout

@devinreams I think we'll want to regroup on this sheet after our meeting on new path forward; this will give us a better way to prioritize each line item (and break them out into separate issues as needed)

**Comment by devinreams** [comment]
Close this and new story for prioritization needed
