### ISSUE TITLE
Update search focus state to match current build

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#638]

**Comment by jimporter** [comment]
What's needed for this issue? I can't tell from the summary...

**Comment by nickbrandt** [comment]
@jimporter This is just a design chore, as we needed to update the current search/filter focus state in the designs to match Photon (and what is currently implemented in the extension).

**Comment by jimporter** [comment]
Ok cool, just wanted to make sure there wasn't anything you guys needed from me.
