### ISSUE TITLE
Move user-facing docs to mozilla-lockbox

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#649]
Currently, the user-facing docs for the desktop extension are part of this repo. Unfortunately, that means that we can't deploy our *developer* docs to this repo's github.io page. Let's work to move the user-facing docs to our main project page so that we can use this one for dev docs. That should make it easier for people who want to be involved in working on Lockbox to find the relevant dev docs.

**Comment by devinreams** [comment]
>Unfortunately, that means that we can't deploy our developer docs to this repo's github.io page

Ehhh, I think we can, actually. Why not both? 😉 

I'll open a quick PR to get all pages published under a "Developer Guides" sub-section so they're present and available, but a little bit buried.
