### ISSUE TITLE
Documentation says we support sync, when we don't (yet)

### ISSUE THREAD

**Issue by joinnusdev** [mozilla-lockbox/lockbox-extension#670]
If I understood correctly, my passwords should be accesible from any computer synced with my Firefox Account, but I can only access them in the computer I've created them, when I log in in another computer I see none.

This is from the FAQ:

> Do Lockbox entries sync to other computers with Lockbox installed?
> 
> Yes, if you secure Lockbox with a Firefox Account.

**Comment by jimporter** [comment]
I think that documentation is actually from the future, since we're still working on implementing sync: see #492. Let's convert this issue into amending the documentation so that it reflects what we have now.
