### ISSUE TITLE
[pi] Remove the munger

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#676]
Task: responsibly remove the [munger](https://github.com/mozilla-lockbox/lockbox-extension/blob/master/test/integration/pages/util/util.py) along with the accompanying touch points this function is used in throughout our page objects.

Note, there is a dependency that we need to wait on, add annotations of our React components to the DOM in dev builds #664. Once this has landed we can move towards using the annotated CSS selectors for the tests to hook into.

**Comment by devinreams** [comment]
>> Once this has landed we can move towards using the annotated CSS selectors
>> 

@jimporter @mbrandt I can’t recall if you two discussed and agreed. Who is responsible for implementing #664? I see @jimporter self assigned but wasn’t sure if that was him explicitly volunteering to do the work...

**Comment by jimporter** [comment]
I don't think we should actually *remove* this, but we can move away from using it where possible. We may want to actually check that styles are updating as expected in certain cases.

**Comment by m8ttyB** [comment]
@jimporter good call, I let me change this to "responsibly remove." Admittedly there are other options for ensuring styles are updating as expected that we may want to consider scoping and working into the test suite. The current suite of tests is meant to functionally check the behaviors of LB and not the visual aspects of it.

**Comment by m8ttyB** [comment]
@devinreams It's up for discussion, but I think it's safer for the dev team to implement #664.

**Comment by m8ttyB** [comment]
Closing this out. If in the future we want to re-approach this work, we can do so incrementally as the test suite expands.
