### ISSUE TITLE
Decide on changelog convention and when to start using it

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#76]
- [ ] Which convention do we like best?

- [ ] When shall we cut our first release / changelog?

Follow-on from #68

**Comment by linuxwolf** [comment]
1. I've liked the simplicity of eslint's ... but angular's seems to be the most popular
2. October 6

**Comment by devinreams** [comment]
@jimporter did you have a strong preference on how to consistently write our merge commit descriptions to adhere to a convention that can help us automatically generate a changelog?

I believe @linuxwolf proposed angular and appears to have started using that on datastore...

Related: https://github.com/mozilla-lockbox/lockbox-extension/pull/158

**Comment by jimporter** [comment]
@devinreams I tend to prefer manually managing changelogs because then I can do fancy things like cross-referencing the documentation so people can get more details about the thing that was changed, but if we're set on using some kind of automatic changelog generator, I suppose I don't have a preference.

**Comment by jimporter** [comment]
@devinreams Actually, there *is* a possible reason we might want to avoid putting changelogs in commit messages, but it's a bit too late in the evening for an essay about how to make tree sheriffs happy. I'll try to remember to bring it up at the meeting tomorrow, but if I forget, just remind me. :)

**Comment by sandysage** [comment]
- [ ] release notes

**Comment by sandysage** [comment]
Release notes drafted and pull request [here](https://github.com/mozilla-lockbox/lockbox-extension/pull/176)

**Comment by linuxwolf** [comment]
After talking with @sandysage , using `convential-changelog` might not be worth it.

The log should be something that the intended audience can be pointed to and will understand.  I'm not sure we can do that adequately with just `conventional-changelog` and any preset.

For things where the audience is developers, I think a commit log format makes sense, and using something that `convential-changelog` understands is worthwhile, at least as a starting point if not the end-all.  For things where the audience is users for an "app", the value is a lot less.

**Comment by devinreams** [comment]
I really like the release notes approach and agree with what you all have concluded here (being more product/user oriented). Great points 👍

**Comment by linuxwolf** [comment]
Resolved in #176
