### ISSUE TITLE
Document CODEOWNERS

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#78]
May be overkill but may also be good to start splitting up (backend vs frontend vs locales).

Especially helpful for automating PR reviewers.

https://help.github.com/articles/about-codeowners/

- [x] add a draft
- [ ] un-comment l10n review after first string freeze

**Comment by pdehaan** [comment]
Possibly fixed via #89

**Comment by devinreams** [comment]
I'll circle back when we freeze strings to make sure we "uncomment" Flod. 😄

**Comment by linuxwolf** [comment]
Closing as done with #89.

We can open a new issue for l10n concerns.
