### ISSUE TITLE
Run the WebExtension code through addons-linter

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#86]
Should we lint the WebExtension itself with https://github.com/mozilla/addons-linter?

There's a bunch of warnings about eval and unsafe assignment. Would any of this be useful and a good second check for us to run at some point?

**Comment by jimporter** [comment]
Not really, no. 99% of those warnings are from React/Redux, which I doubt we're going to fix. I honestly don't put much stock in the add-on linter except that, for my own add-ons, I try to reduce the number of warnings I get so my reviews go faster on AMO.

**Comment by devinreams** [comment]
>99% of those warnings are from React/Redux, which I doubt we're going to fix

I assumed so. Might be worth revisiting as the extension evolves... will close for now.
