### ISSUE TITLE
Switch from 'jpm' to 'web-ext'?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#95]
Currently we're using [**jpm**](http://npm.im/jpm) and not the newer [**web-ext**](http://npm.im/web-ext) in package.json:

https://github.com/mozilla-lockbox/lockbox-extension/blob/dd5823840de4bb1f8104577a6b62920d8a6fa6f6/package.json#L99

https://github.com/mozilla-lockbox/lockbox-extension/blob/dd5823840de4bb1f8104577a6b62920d8a6fa6f6/package.json#L33

Not sure if we shouldn't be using **web-ext** instead, since it's more awesome.

**Comment by jimporter** [comment]
Does `web-ext` let us work with classic XPCOM add-ons? We're doing an embedded WebExtension now because we'll eventually need XPCOM for form autofill.

**Comment by jimporter** [comment]
Closing this for now, since `web-ext` doesn't like XPCOM. Maybe one day we can switch over though (e.g. when there's a better alternative to embedded WebExtensions like we're doing now).
