### ISSUE TITLE
Format code using prettier?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#97]
We use it on a few other repos... Not sure how people feel about it here.

This should auto-format all the src/* files. The diff is ~~a bit~~ _super_ noisy though.

```json
"format": "prettier '{,src/**/,test/**/}*.{css,js,json}' --trailing-comma=es5 --write",
"postformat": "npm run autolint -- --fix",
```

**Comment by jimporter** [comment]
I'm not a fan of auto-formatting myself (aside from lint fixes). I do my best to keep the code readable already, and from what I've read about `prettier` (which to be fair isn't much), it would undo a lot of that conscious effort.

**Comment by devinreams** [comment]
I don't see a strong desire to do this right now.

What's more important in my mind is linting #352. Can we close this in favor of that (gets the consistency we care about)?

**Comment by pdehaan** [comment]
Works for me!

![](https://media.giphy.com/media/pu6PQqp3OA1xu/giphy.gif)
