### ISSUE TITLE
browser-style is bad :C

### ISSUE THREAD

**Issue by jimporter** [mozilla-lockbox/lockbox-extension#99]
It turns out `browser-style` has some significant limitations. First, it hasn't been updated for Photon. More importantly though, it adds some unnecessary requirements to how checkboxes and radio buttons are defined in the document (namely, a `<label>` must immediately follow them. This puts a bit of a crimp in our style, since we use the convention of *wrapping* our elements with `<label>`s so that we never have to use IDs in our React components. It's possible to avoid this with different CSS (taking advantage of `appearance`), but that means writing a bunch of our own CSS.

The "easy way" is to write our own CSS for checkboxes and radio buttons, but otherwise retain the old style. We could also try to copy the CSS from `about:preferences`, but that page is written in XUL, so the translation won't be 1:1. If we do that though, we could fix <https://bugzilla.mozilla.org/show_bug.cgi?id=1398606> along the way, which I'm sure the browser devs would appreciate.

(We could also give in and use IDs - or even generate unique IDs for every relevant element - but I'd rather not.)

@devinreams, @linuxwolf: Thoughts?

**Comment by linuxwolf** [comment]
I'm for whatever gets us something pleasing without spending much time on it.  IDs are "icky", but there are worse things that could be done.  But I'll defer to others; and this seems like a good candidate for the Oct work week.

**Comment by devinreams** [comment]
@jimporter as discussed this week, we're intentionally moving away from browser-style at this point and re-implementing CSS ourselves. 

I'm going to close this out as stale and superseded by #166

Please correct me if wrong.
